changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New and improved
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - '*'
