// SPDX-License-Identifier: MIT

namespace PromptMeUp.Services;

internal static partial class FeatureText
{
    private static readonly Dictionary<string, string[]> Entries = new(StringComparer.Ordinal)
    {
        ["Recipe.Help"] = ["Personal command recipes", "Ricette personali di comandi", "Recettes de commandes personnelles", "Persönliche Befehlsrezepte", "Recetas personales de comandos", "Công thức lệnh cá nhân"],
        ["Recipe.Usage"] = ["Use --recipes [list|show <name>|run <name>|save <name> --from-plan <id>|import --file <json>|export <name> --output <json>].", "Usa --recipes [list|show <nome>|run <nome>|save <nome> --from-plan <id>|import --file <json>|export <nome> --output <json>].", "Utilisez --recipes [list|show <nom>|run <nom>|save <nom> --from-plan <id>|import --file <json>|export <nom> --output <json>].", "Nutzen Sie --recipes [list|show <Name>|run <Name>|save <Name> --from-plan <id>|import --file <json>|export <Name> --output <json>].", "Usa --recipes [list|show <nombre>|run <nombre>|save <nombre> --from-plan <id>|import --file <json>|export <nombre> --output <json>].", "Dùng --recipes [list|show <tên>|run <tên>|save <tên> --from-plan <id>|import --file <json>|export <tên> --output <json>]."],
        ["Recipe.Invalid"] = ["Invalid or unsupported recipe. Check schema, names, bounds, prerequisites, and credential-free commands.", "Ricetta non valida o non supportata. Controlla schema, nomi, limiti, prerequisiti e comandi privi di credenziali.", "Recette invalide ou non prise en charge. Vérifiez schéma, noms, limites, prérequis et absence d'identifiants.", "Ungültiges oder nicht unterstütztes Rezept. Schema, Namen, Grenzen, Voraussetzungen und zugangsdatenfreie Befehle prüfen.", "Receta inválida o no compatible. Revisa esquema, nombres, límites, requisitos y comandos sin credenciales.", "Công thức không hợp lệ hoặc không hỗ trợ. Kiểm tra lược đồ, tên, giới hạn, điều kiện và lệnh không chứa thông tin xác thực."],
        ["Recipe.Limit"] = ["The local library supports up to 200 recipes.", "La libreria locale supporta fino a 200 ricette.", "La bibliothèque locale accepte jusqu'à 200 recettes.", "Die lokale Bibliothek unterstützt bis zu 200 Rezepte.", "La biblioteca local admite hasta 200 recetas.", "Thư viện cục bộ hỗ trợ tối đa 200 công thức."],
        ["Recipe.ReadError"] = ["Cannot read this recipe JSON file.", "Impossibile leggere questo file JSON di ricetta.", "Impossible de lire ce fichier JSON de recette.", "Diese Rezept-JSON-Datei kann nicht gelesen werden.", "No se puede leer este archivo JSON de receta.", "Không thể đọc tệp JSON công thức này."],
        ["Recipe.SaveError"] = ["Choose a writable new JSON destination or an unused recipe name.", "Scegli una nuova destinazione JSON scrivibile o un nome di ricetta inutilizzato.", "Choisissez une nouvelle destination JSON accessible ou un nom de recette inutilisé.", "Neues beschreibbares JSON-Ziel oder unbenutzten Rezeptnamen wählen.", "Elige un nuevo destino JSON escribible o un nombre de receta sin usar.", "Chọn đường dẫn JSON mới ghi được hoặc tên công thức chưa dùng."],
        ["Recipe.Incomplete"] = ["Only a fully completed and confirmed plan can be saved as a successful recipe.", "Solo un piano completamente concluso e confermato può diventare una ricetta riuscita.", "Seul un plan entièrement terminé et confirmé peut devenir une recette réussie.", "Nur ein vollständig abgeschlossener und bestätigter Plan kann als erfolgreiches Rezept gespeichert werden.", "Solo un plan totalmente completado y confirmado puede guardarse como receta exitosa.", "Chỉ kế hoạch hoàn thành và xác nhận đầy đủ mới lưu được thành công thức thành công."],
        ["Recipe.Parameters"] = ["Provide every parameter once, up to 1024 characters each, without credentials.", "Fornisci ogni parametro una volta, entro 1024 caratteri ciascuno, senza credenziali.", "Fournissez chaque paramètre une fois, 1024 caractères maximum, sans identifiants.", "Jeden Parameter einmal mit höchstens 1024 Zeichen ohne Zugangsdaten angeben.", "Proporciona cada parámetro una vez, hasta 1024 caracteres, sin credenciales.", "Nhập mỗi tham số một lần, tối đa 1024 ký tự, không có thông tin xác thực."],
        ["Recipe.Name"] = ["Name", "Nome", "Nom", "Name", "Nombre", "Tên"],
        ["Recipe.Description"] = ["Description", "Descrizione", "Description", "Beschreibung", "Descripción", "Mô tả"],
        ["Recipe.Empty"] = ["No recipes yet. Save a completed plan or import a reviewed JSON definition.", "Nessuna ricetta. Salva un piano completato o importa una definizione JSON revisionata.", "Aucune recette. Enregistrez un plan terminé ou importez une définition JSON vérifiée.", "Noch keine Rezepte. Abgeschlossenen Plan speichern oder geprüftes JSON importieren.", "Aún no hay recetas. Guarda un plan completado o importa una definición JSON revisada.", "Chưa có công thức. Lưu kế hoạch hoàn thành hoặc nhập định nghĩa JSON đã kiểm tra."],
        ["Recipe.CurrentDirectory"] = ["Uses the current directory", "Usa la cartella corrente", "Utilise le dossier courant", "Verwendet das aktuelle Verzeichnis", "Usa el directorio actual", "Dùng thư mục hiện tại"],
        ["Recipe.ConfirmSave"] = ["Save the displayed recipe to {0}?", "Salvare la ricetta mostrata in {0}?", "Enregistrer la recette affichée dans {0} ?", "Angezeigtes Rezept in {0} speichern?", "¿Guardar la receta mostrada en {0}?", "Lưu công thức đã hiển thị vào {0}?"],
        ["Recipe.Prerequisites"] = ["Have you checked the displayed prerequisites and working directory?", "Hai controllato i prerequisiti e la cartella di lavoro mostrati?", "Avez-vous vérifié les prérequis et le dossier de travail affichés ?", "Haben Sie Voraussetzungen und Arbeitsverzeichnis geprüft?", "¿Has comprobado los requisitos y el directorio de trabajo mostrados?", "Bạn đã kiểm tra điều kiện và thư mục làm việc được hiển thị chưa?"],
        ["Recipe.Saved"] = ["Recipe saved: {0}", "Ricetta salvata: {0}", "Recette enregistrée : {0}", "Rezept gespeichert: {0}", "Receta guardada: {0}", "Đã lưu công thức: {0}"],
        ["Preview.Help"] = ["Preview file effects", "Anteprima degli effetti sui file", "Aperçu des effets sur les fichiers", "Dateiauswirkungen anzeigen", "Vista previa de efectos en archivos", "Xem trước tác động lên tệp"],
        ["Preview.Usage"] = ["Use --preview copy|move|rename|delete --file <source>; copy/move require --output <existing-directory>, rename requires --prefix <text>. Optional: --pattern <glob>.", "Usa --preview copy|move|rename|delete --file <sorgente>; copy/move richiedono --output <cartella-esistente>, rename richiede --prefix <testo>. Facoltativo: --pattern <glob>.", "Utilisez --preview copy|move|rename|delete --file <source> ; copy/move exigent --output <dossier-existant>, rename exige --prefix <texte>. Option : --pattern <glob>.", "Nutzen Sie --preview copy|move|rename|delete --file <Quelle>; copy/move benötigen --output <vorhandenes-Verzeichnis>, rename benötigt --prefix <Text>. Optional: --pattern <glob>.", "Usa --preview copy|move|rename|delete --file <origen>; copy/move requieren --output <directorio-existente>, rename requiere --prefix <texto>. Opcional: --pattern <glob>.", "Dùng --preview copy|move|rename|delete --file <nguồn>; copy/move cần --output <thư-mục-có-sẵn>, rename cần --prefix <văn-bản>. Tùy chọn: --pattern <glob>."],
        ["Preview.Destination"] = ["Choose an existing destination directory.", "Scegli una cartella di destinazione esistente.", "Choisissez un dossier de destination existant.", "Vorhandenes Zielverzeichnis wählen.", "Elige un directorio de destino existente.", "Chọn thư mục đích đã tồn tại."],
        ["Preview.TooMany"] = ["Preview limit reached ({0} files). Narrow the source or filter.", "Limite anteprima raggiunto ({0} file). Restringi la sorgente o il filtro.", "Limite atteinte ({0} fichiers). Réduisez la source ou le filtre.", "Vorschaulimit erreicht ({0} Dateien). Quelle oder Filter eingrenzen.", "Límite de vista previa alcanzado ({0} archivos). Reduce el origen o filtro.", "Đạt giới hạn xem trước ({0} tệp). Thu hẹp nguồn hoặc bộ lọc."],
        ["Preview.Changed"] = ["The snapshot changed. Generate a new preview before continuing.", "Lo stato è cambiato. Genera una nuova anteprima prima di continuare.", "L'état a changé. Créez un nouvel aperçu avant de continuer.", "Der Zustand hat sich geändert. Neue Vorschau erstellen.", "El estado cambió. Genera otra vista previa antes de continuar.", "Trạng thái đã thay đổi. Tạo bản xem trước mới trước khi tiếp tục."],
        ["Preview.Empty"] = ["No matching files.", "Nessun file corrispondente.", "Aucun fichier correspondant.", "Keine passenden Dateien.", "No hay archivos coincidentes.", "Không có tệp phù hợp."],
        ["Preview.ReadError"] = ["Cannot inspect these file paths.", "Impossibile ispezionare questi percorsi.", "Impossible d'inspecter ces chemins.", "Diese Pfade können nicht geprüft werden.", "No se pueden inspeccionar estas rutas.", "Không thể kiểm tra các đường dẫn này."],
        ["Preview.Links"] = ["Symbolic links and reparse points are not supported by this preview.", "Questa anteprima non supporta link simbolici o reparse point.", "Cet aperçu ne prend pas en charge les liens symboliques et points de réanalyse.", "Symbolische Links und Analysepunkte werden nicht unterstützt.", "Esta vista previa no admite enlaces simbólicos ni puntos de reanálisis.", "Bản xem trước không hỗ trợ liên kết tượng trưng và reparse point."],
        ["Preview.Snapshot"] = ["Local snapshot only; other processes can still change files. No recursive directories or arbitrary shell commands are simulated.", "Solo stato locale corrente; altri processi possono ancora cambiare i file. Non vengono simulati alberi ricorsivi o comandi shell arbitrari.", "Instantané local ; d'autres processus peuvent encore modifier les fichiers. Aucune simulation de dossiers récursifs ou commandes arbitraires.", "Lokale Momentaufnahme; andere Prozesse können Dateien weiter ändern. Keine Simulation rekursiver Verzeichnisse oder beliebiger Shell-Befehle.", "Solo estado local actual; otros procesos pueden cambiar archivos. No se simulan directorios recursivos ni comandos arbitrarios.", "Chỉ ảnh chụp trạng thái cục bộ; tiến trình khác vẫn có thể thay đổi tệp. Không mô phỏng thư mục đệ quy hay lệnh shell tùy ý."],
        ["Preview.Source"] = ["Source", "Sorgente", "Source", "Quelle", "Origen", "Nguồn"],
        ["Preview.Target"] = ["Destination / effect", "Destinazione / effetto", "Destination / effet", "Ziel / Auswirkung", "Destino / efecto", "Đích / tác động"],
        ["Preview.Bytes"] = ["Bytes", "Byte", "Octets", "Bytes", "Bytes", "Byte"],
        ["Preview.Delete"] = ["Delete file", "Elimina file", "Supprimer le fichier", "Datei löschen", "Eliminar archivo", "Xóa tệp"],
        ["Preview.Collision"] = ["Collision: nothing will run.", "Collisione: nessuna esecuzione.", "Collision : aucune exécution.", "Kollision: keine Ausführung.", "Colisión: no se ejecutará nada.", "Xung đột: không chạy gì."],
        ["Preview.Ready"] = ["Snapshot checked", "Stato controllato", "État vérifié", "Zustand geprüft", "Estado comprobado", "Đã kiểm tra trạng thái"],
        ["Preview.Total"] = ["{0} files · {1:N0} bytes", "{0} file · {1:N0} byte", "{0} fichiers · {1:N0} octets", "{0} Dateien · {1:N0} Bytes", "{0} archivos · {1:N0} bytes", "{0} tệp · {1:N0} byte"],
        ["Preview.Review"] = ["Review each command for separate approval?", "Rivedere ogni comando per una conferma separata?", "Examiner chaque commande pour un accord distinct ?", "Jeden Befehl einzeln zur Genehmigung prüfen?", "¿Revisar cada comando para aprobación separada?", "Xem từng lệnh để cấp quyền riêng?"],
        ["Plan.Help"] = ["Guide and resume a plan", "Guida e riprendi un piano", "Guider et reprendre un plan", "Plan begleiten und fortsetzen", "Guiar y reanudar un plan", "Hướng dẫn và tiếp tục kế hoạch"],
        ["Plan.Usage"] = ["Use --plan <goal> or --plan --resume <id>.", "Usa --plan <obiettivo> oppure --plan --resume <id>.", "Utilisez --plan <objectif> ou --plan --resume <id>.", "Verwenden Sie --plan <Ziel> oder --plan --resume <id>.", "Usa --plan <objetivo> o --plan --resume <id>.", "Dùng --plan <mục-tiêu> hoặc --plan --resume <id>."],
        ["Plan.Invalid"] = ["Invalid or unsupported plan. Require 1–8 bounded steps with commands and verification.", "Piano non valido o non supportato. Servono 1–8 passi limitati con comandi e verifica.", "Plan invalide ou non pris en charge. Il faut 1 à 8 étapes bornées avec commandes et vérification.", "Ungültiger oder nicht unterstützter Plan. Erforderlich sind 1–8 begrenzte Schritte mit Befehlen und Prüfung.", "Plan inválido o no compatible. Se requieren 1–8 pasos acotados con comandos y verificación.", "Kế hoạch không hợp lệ hoặc không hỗ trợ. Cần 1–8 bước có giới hạn với lệnh và kiểm tra."],
        ["Plan.Busy"] = ["This plan is already open in another process.", "Questo piano è già aperto in un altro processo.", "Ce plan est déjà ouvert dans un autre processus.", "Dieser Plan ist bereits in einem anderen Prozess geöffnet.", "Este plan ya está abierto en otro proceso.", "Kế hoạch đang mở trong tiến trình khác."],
        ["Plan.LoadError"] = ["Cannot load this saved plan.", "Impossibile caricare questo piano salvato.", "Impossible de charger ce plan enregistré.", "Gespeicherter Plan kann nicht geladen werden.", "No se puede cargar este plan guardado.", "Không thể tải kế hoạch đã lưu."],
        ["Plan.Step"] = ["Step and expected result", "Passo e risultato atteso", "Étape et résultat attendu", "Schritt und erwartetes Ergebnis", "Paso y resultado esperado", "Bước và kết quả mong đợi"],
        ["Plan.Status"] = ["Status", "Stato", "État", "Status", "Estado", "Trạng thái"],
        ["Plan.Pending"] = ["Pending", "Da eseguire", "En attente", "Ausstehend", "Pendiente", "Chờ"],
        ["Plan.Running"] = ["Outcome unknown", "Esito sconosciuto", "Résultat inconnu", "Ergebnis unbekannt", "Resultado desconocido", "Kết quả chưa rõ"],
        ["Plan.NeedsReview"] = ["Needs verification", "Richiede verifica", "Vérification requise", "Prüfung erforderlich", "Requiere verificación", "Cần kiểm tra"],
        ["Plan.Completed"] = ["Completed and confirmed", "Completato e confermato", "Terminé et confirmé", "Abgeschlossen und bestätigt", "Completado y confirmado", "Đã hoàn thành và xác nhận"],
        ["Plan.Start"] = ["Start guidance? Each command needs separate approval.", "Avviare la guida? Ogni comando richiede una conferma separata.", "Démarrer le guide ? Chaque commande nécessite un accord distinct.", "Anleitung starten? Jeder Befehl benötigt eine eigene Zustimmung.", "¿Iniciar la guía? Cada comando necesita aprobación separada.", "Bắt đầu hướng dẫn? Mỗi lệnh cần cấp quyền riêng."],
        ["Plan.Outcome"] = ["Does the observed result match: {0}?", "Il risultato osservato corrisponde a: {0}?", "Le résultat observé correspond-il à : {0} ?", "Entspricht das beobachtete Ergebnis: {0}?", "¿El resultado observado coincide con: {0}?", "Kết quả quan sát có khớp với: {0}?"],
        ["Plan.Directory"] = ["Resume from the original directory: {0}", "Riprendi dalla cartella originale: {0}", "Reprenez depuis le dossier original : {0}", "Im ursprünglichen Verzeichnis fortsetzen: {0}", "Reanuda desde el directorio original: {0}", "Tiếp tục từ thư mục gốc: {0}"],
        ["Plan.Recheck"] = ["Verify current state before continuing. The original action will not be repeated.", "Verifica lo stato attuale prima di continuare. L'azione originale non verrà ripetuta.", "Vérifiez l'état actuel avant de continuer. L'action originale ne sera pas répétée.", "Prüfen Sie den aktuellen Zustand. Die ursprüngliche Aktion wird nicht wiederholt.", "Verifica el estado actual antes de continuar. La acción original no se repetirá.", "Kiểm tra trạng thái hiện tại trước khi tiếp tục. Thao tác gốc sẽ không lặp lại."],
        ["Plan.Stopped"] = ["Plan paused: resolve the discrepancy, then resume to verify. No further action was started.", "Piano sospeso: risolvi la discrepanza, poi riprendi per verificare. Nessuna azione successiva è stata avviata.", "Plan suspendu : résolvez l'écart, puis reprenez pour vérifier. Aucune action suivante n'a démarré.", "Plan pausiert: Abweichung beheben und zur Prüfung fortsetzen. Keine weitere Aktion wurde gestartet.", "Plan pausado: resuelve la discrepancia y reanuda para verificar. No se inició otra acción.", "Kế hoạch tạm dừng: xử lý sai lệch rồi tiếp tục kiểm tra. Chưa bắt đầu thao tác tiếp theo."],
        ["Script.Help"] = ["Create or revise a PowerShell script", "Crea o modifica uno script PowerShell", "Créer ou modifier un script PowerShell", "PowerShell-Skript erstellen oder überarbeiten", "Crear o modificar un script PowerShell", "Tạo hoặc sửa tập lệnh PowerShell"],
        ["Script.OutputOption"] = ["--output requires one new .ps1 destination.", "--output richiede una nuova destinazione .ps1.", "--output exige une nouvelle destination .ps1.", "--output benötigt ein neues .ps1-Ziel.", "--output requiere un destino .ps1 nuevo.", "--output cần đường dẫn .ps1 mới."],
        ["Script.Usage"] = ["Use --script <request> [--file <source>] [--output <new.ps1>].", "Usa --script <richiesta> [--file <sorgente>] [--output <nuovo.ps1>].", "Utilisez --script <demande> [--file <source>] [--output <nouveau.ps1>].", "Verwenden Sie --script <Anfrage> [--file <Quelle>] [--output <neu.ps1>].", "Usa --script <petición> [--file <origen>] [--output <nuevo.ps1>].", "Dùng --script <yêu-cầu> [--file <nguồn>] [--output <mới.ps1>]."],
        ["Script.Invalid"] = ["Invalid script: require non-empty source up to 12000 characters without credentials or redaction markers.", "Script non valido: serve codice non vuoto, entro 12000 caratteri, senza credenziali o marcatori di redazione.", "Script invalide : code non vide, 12000 caractères maximum, sans identifiants ni marqueurs de masquage.", "Ungültiges Skript: nicht leer, höchstens 12000 Zeichen, ohne Zugangsdaten oder Schwärzungsmarker.", "Script inválido: código no vacío de hasta 12000 caracteres sin credenciales ni marcas de ocultación.", "Tập lệnh không hợp lệ: cần mã không rỗng, tối đa 12000 ký tự, không chứa thông tin xác thực hay dấu đã lọc."],
        ["Script.SaveError"] = ["Cannot save: choose a writable destination that does not already exist.", "Salvataggio impossibile: scegli una destinazione scrivibile che non esista già.", "Échec de sauvegarde : choisissez une destination accessible qui n'existe pas.", "Speichern fehlgeschlagen: Wählen Sie ein beschreibbares, noch nicht vorhandenes Ziel.", "No se puede guardar: elige un destino escribible que no exista.", "Không thể lưu: chọn đường dẫn ghi được và chưa tồn tại."],
        ["Script.Source"] = ["Full source", "Codice completo", "Code complet", "Vollständiger Quelltext", "Código completo", "Toàn bộ mã"],
        ["Script.Action"] = ["Choose the next step", "Scegli il prossimo passo", "Choisissez la prochaine étape", "Nächsten Schritt wählen", "Elige el siguiente paso", "Chọn bước tiếp theo"],
        ["Script.Cancel"] = ["Finish without saving", "Termina senza salvare", "Terminer sans enregistrer", "Ohne Speichern beenden", "Terminar sin guardar", "Kết thúc không lưu"],
        ["Script.Save"] = ["Save to a new file", "Salva in un nuovo file", "Enregistrer dans un nouveau fichier", "In neuer Datei speichern", "Guardar en un archivo nuevo", "Lưu vào tệp mới"],
        ["Script.Validate"] = ["Review the syntax-check command", "Rivedi il comando di controllo sintassi", "Vérifier la commande d'analyse syntaxique", "Befehl zur Syntaxprüfung prüfen", "Revisar el comando de validación sintáctica", "Xem lệnh kiểm tra cú pháp"],
        ["Script.Revise"] = ["Request a revision", "Richiedi una modifica", "Demander une modification", "Überarbeitung anfordern", "Solicitar una modificación", "Yêu cầu chỉnh sửa"],
        ["Script.Confirm"] = ["Save the displayed source to {0}?", "Salvare il codice mostrato in {0}?", "Enregistrer le code affiché dans {0} ?", "Angezeigten Quelltext in {0} speichern?", "¿Guardar el código mostrado en {0}?", "Lưu mã đã hiển thị vào {0}?"],
        ["Script.Destination"] = ["New .ps1 destination", "Nuova destinazione .ps1", "Nouvelle destination .ps1", "Neues .ps1-Ziel", "Nuevo destino .ps1", "Đường dẫn .ps1 mới"],
        ["Script.Saved"] = ["Saved: {0}", "Salvato: {0}", "Enregistré : {0}", "Gespeichert: {0}", "Guardado: {0}", "Đã lưu: {0}"],
        ["Script.ValidationNote"] = ["Syntax checks do not prove correctness or safety. AnalyzerAvailable reports whether optional PSScriptAnalyzer was used.", "La sintassi non dimostra correttezza o sicurezza. AnalyzerAvailable indica se è stato usato PSScriptAnalyzer opzionale.", "La syntaxe ne prouve ni correction ni sécurité. AnalyzerAvailable indique l'utilisation du module facultatif PSScriptAnalyzer.", "Syntaxprüfungen beweisen weder Korrektheit noch Sicherheit. AnalyzerAvailable zeigt die Nutzung des optionalen PSScriptAnalyzer.", "La sintaxis no garantiza corrección ni seguridad. AnalyzerAvailable indica si se usó PSScriptAnalyzer opcional.", "Kiểm tra cú pháp không chứng minh tính đúng đắn hay an toàn. AnalyzerAvailable cho biết có dùng PSScriptAnalyzer tùy chọn hay không."],
        ["Script.Revision"] = ["Describe the change", "Descrivi la modifica", "Décrivez la modification", "Änderung beschreiben", "Describe el cambio", "Mô tả thay đổi"],
        ["Diagnose.Help"] = ["Diagnose errors and logs", "Diagnostica errori e log", "Diagnostiquer les erreurs et journaux", "Fehler und Protokolle diagnostizieren", "Diagnosticar errores y registros", "Chẩn đoán lỗi và nhật ký"],
        ["Input.FileOption"] = ["--file requires one path and may appear once.", "--file richiede un percorso e può apparire una sola volta.", "--file exige un chemin et ne peut apparaître qu'une fois.", "--file benötigt einen Pfad und darf nur einmal vorkommen.", "--file requiere una ruta y solo puede aparecer una vez.", "--file cần một đường dẫn và chỉ được dùng một lần."],
        ["Input.SourceConflict"] = ["Choose one input source: text, --file, or a pipe.", "Scegli una fonte: testo, --file o una pipe.", "Choisissez une source : texte, --file ou un pipe.", "Wählen Sie eine Quelle: Text, --file oder Pipe.", "Elige una fuente: texto, --file o una tubería.", "Chọn một nguồn: văn bản, --file hoặc pipe."],
        ["Input.FileError"] = ["Cannot read this text file.", "Impossibile leggere questo file di testo.", "Impossible de lire ce fichier texte.", "Diese Textdatei kann nicht gelesen werden.", "No se puede leer este archivo de texto.", "Không thể đọc tệp văn bản này."],
        ["Input.Empty"] = ["Provide non-empty input.", "Fornisci un testo non vuoto.", "Fournissez un texte non vide.", "Geben Sie einen nicht leeren Text ein.", "Proporciona texto no vacío.", "Cung cấp văn bản không rỗng."],
        ["Input.TooLong"] = ["Input exceeds {0} characters. Select a smaller excerpt.", "Il testo supera {0} caratteri. Seleziona un estratto più breve.", "Le texte dépasse {0} caractères. Sélectionnez un extrait plus court.", "Die Eingabe überschreitet {0} Zeichen. Wählen Sie einen kürzeren Ausschnitt.", "El texto supera {0} caracteres. Selecciona un fragmento menor.", "Đầu vào vượt quá {0} ký tự. Chọn đoạn ngắn hơn."],
        ["Input.Timeout"] = ["Input did not finish within 30 seconds.", "L'input non è terminato entro 30 secondi.", "La lecture n'est pas terminée après 30 secondes.", "Die Eingabe wurde nicht innerhalb von 30 Sekunden abgeschlossen.", "La entrada no terminó en 30 segundos.", "Đầu vào chưa kết thúc sau 30 giây."],
        ["Input.SecretArgument"] = ["Do not pass credentials as command-line arguments. Use a sanitized file or interactive input.", "Non passare credenziali negli argomenti. Usa un file redatto o l'input interattivo.", "Ne transmettez pas d'identifiants en arguments. Utilisez un fichier expurgé ou la saisie interactive.", "Übergeben Sie keine Zugangsdaten als Argumente. Verwenden Sie eine bereinigte Datei oder interaktive Eingabe.", "No pases credenciales como argumentos. Usa un archivo depurado o entrada interactiva.", "Không truyền thông tin xác thực qua đối số. Dùng tệp đã lọc hoặc nhập tương tác."],
        ["Input.Sharing"] = ["The selected text is sent to the AI provider after recognizable credentials are redacted.", "Il testo selezionato viene inviato al provider AI dopo la redazione delle credenziali riconoscibili.", "Le texte sélectionné est envoyé au fournisseur IA après masquage des identifiants reconnaissables.", "Der ausgewählte Text wird nach Entfernung erkennbarer Zugangsdaten an den KI-Anbieter gesendet.", "El texto seleccionado se envía al proveedor de IA tras ocultar las credenciales reconocibles.", "Văn bản đã chọn được gửi đến nhà cung cấp AI sau khi lọc thông tin xác thực nhận diện được."]
    };

    /// <summary>Resolves a feature string from the complete six-language catalog.</summary>
    internal static bool TryGet(string key, string language, out string value)
    {
        if (!Entries.TryGetValue(key, out var translations))
        {
            value = string.Empty;
            return false;
        }
        var index = language switch { "en" => 0, "it" => 1, "fr" => 2, "de" => 3, "es" => 4, "vi" => 5, _ => throw new ArgumentOutOfRangeException(nameof(language)) };
        value = translations[index];
        return true;
    }
}
