// SPDX-License-Identifier: MIT

using System.Globalization;

namespace PromptMeUp.Services;

public sealed record SupportedLanguage(string Code, string NativeName, string CultureName);

public static class SupportedLanguages
{
    public static IReadOnlyList<SupportedLanguage> All { get; } =
    [
        new("it", "Italiano", "it-IT"),
        new("en", "English", "en-US"),
        new("fr", "Français", "fr-FR"),
        new("de", "Deutsch", "de-DE"),
        new("es", "Español", "es-ES"),
        new("vi", "Tiếng Việt", "vi-VN")
    ];

    public static IReadOnlyList<string> Codes { get; } = All.Select(language => language.Code).ToArray();

    /// <summary>Checks whether a two-letter interface language is advertised by the product.</summary>
    public static bool IsSupported(string? value) =>
        !string.IsNullOrWhiteSpace(value)
        && All.Any(language => string.Equals(language.Code, value.Trim(), StringComparison.OrdinalIgnoreCase));

    /// <summary>Returns the canonical lower-case code for one supported language.</summary>
    public static string Normalize(string value) =>
        All.First(language => string.Equals(language.Code, value.Trim(), StringComparison.OrdinalIgnoreCase)).Code;

    /// <summary>Uses the current UI culture when supported and otherwise selects English.</summary>
    public static string ResolveSystemLanguage()
    {
        var twoLetter = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return IsSupported(twoLetter) ? Normalize(twoLetter) : "en";
    }

    /// <summary>Resolves the display culture used for localized numbers, dates, and text formatting.</summary>
    public static CultureInfo Culture(string language) =>
        CultureInfo.GetCultureInfo(All.First(item => item.Code == Normalize(language)).CultureName);
}

public interface ILocalizationService
{
    string Language { get; }

    CultureInfo Culture { get; }

    void SetLanguage(string language);

    string Text(string key, params object?[] args);
}

public sealed class LocalizationService : ILocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Tagline"] = "Prompt engineering, conversation, and cost insight — locally organized.",
        ["Status.Language"] = "Language",
        ["Status.Model"] = "Model",
        ["Status.ApiKey"] = "API key",
        ["Status.AdminKey"] = "Admin key",
        ["Status.Database"] = "Database",
        ["Status.Ready"] = "ready",
        ["Status.Missing"] = "missing",
        ["Status.Disabled"] = "disabled",
        ["Status.Local"] = "local",
        ["Footer.Command"] = "Command",
        ["Footer.Version"] = "Version",
        ["Footer.Data"] = "Data",
        ["Setup.Title"] = "AI SETUP // PMU-SETUP-01",
        ["Setup.Header"] = "SYSTEM CONFIGURATION",
        ["Setup.Subtitle"] = "First-run configuration. Secrets stay in your Windows user environment.",
        ["Setup.Language"] = "Interface language",
        ["Setup.AiEnabled"] = "Enable the OpenAI provider?",
        ["Setup.KeyStatus"] = "OPENAI_API_KEY status",
        ["Setup.SetKey"] = "Set or change OPENAI_API_KEY now?",
        ["Setup.KeyPrompt"] = "OpenAI API key",
        ["Setup.AdminKeyStatus"] = "OPENAI_ADMIN_KEY status",
        ["Setup.SetAdminKey"] = "Set the optional admin key for organization costs?",
        ["Setup.AdminKeyPrompt"] = "OpenAI admin key",
        ["Setup.Model"] = "Model",
        ["Setup.Reasoning"] = "Thinking effort",
        ["Setup.Detail"] = "Analysis detail",
        ["Setup.Custom"] = "Additional AI instruction (optional)",
        ["Setup.Location"] = "Include Windows location in AI requests?",
        ["Setup.CommandReview"] = "Use optional AI review before command authorization?",
        ["Setup.PromptCaching"] = "Enable OpenAI prompt caching?",
        ["Setup.MemoryLimits"] = "Short-session memory limits",
        ["Setup.MaxTurns"] = "Maximum user turns",
        ["Setup.MaxMessage"] = "Maximum characters per message",
        ["Setup.MaxContext"] = "Maximum context window usage (%)",
        ["Setup.MaxCommandOutput"] = "Maximum command-output characters kept",
        ["Setup.CommandTimeout"] = "Command timeout in seconds",
        ["Setup.Endpoint"] = "OpenAI Responses endpoint",
        ["Setup.Test"] = "Test the AI connection now?",
        ["Setup.Saved"] = "Configuration saved.",
        ["Setup.Cancelled"] = "Setup cancelled; no configuration was saved.",
        ["Setup.Summary"] = "Configuration summary",
        ["Setup.Confirm"] = "Save these settings?",
        ["Setup.Compact"] = "Compact · lowest usage",
        ["Setup.Balanced"] = "Balanced",
        ["Setup.Detailed"] = "Detailed · larger budget",
        ["Model.gpt-5.6-sol"] = "Frontier model for demanding professional work and reasoning.",
        ["Model.gpt-5.6-terra"] = "Balanced intelligence, latency, and cost for everyday work.",
        ["Model.gpt-5.6-luna"] = "Cost-sensitive model for fast, high-volume workloads.",
        ["Model.gpt-5.5"] = "Previous frontier model for complex professional work.",
        ["Model.gpt-5.4"] = "Affordable model for coding and professional work.",
        ["Model.gpt-5.4-mini"] = "Efficient model for focused and high-volume tasks.",
        ["Model.gpt-5.4-nano"] = "Low-cost model for extraction, ranking, and simple tasks.",
        ["Reasoning.none"] = "None",
        ["Reasoning.low"] = "Low",
        ["Reasoning.medium"] = "Medium",
        ["Reasoning.high"] = "High",
        ["Reasoning.xhigh"] = "Very high",
        ["Reasoning.max"] = "Maximum",
        ["Main.Title"] = "Command center",
        ["Main.Choose"] = "Choose an action",
        ["Main.Chat"] = "Interactive AI chat",
        ["Main.Query"] = "Single prompt",
        ["Main.Costs"] = "Usage and costs",
        ["Main.Status"] = "Application status",
        ["Main.Setup"] = "AI setup",
        ["Main.Test"] = "Test AI connection",
        ["Main.Font"] = "Install Nerd Font",
        ["Main.Exit"] = "Exit",
        ["Query.Prompt"] = "Enter your prompt",
        ["Query.Response"] = "Model response",
        ["Query.Empty"] = "The prompt cannot be empty.",
        ["Chat.Title"] = "Interactive chat",
        ["Chat.Hint"] = "Commands: /run <command>, /exit, /clear, /costs, /status",
        ["Chat.You"] = "You",
        ["Chat.Assistant"] = "PromptMeUp",
        ["Chat.Cleared"] = "Conversation cleared.",
        ["Chat.Exit"] = "Chat closed.",
        ["Chat.Pruned"] = "Active context removed {0} old message(s); the audit ledger remains complete.",
        ["Test.Title"] = "AI connection test",
        ["Test.Success"] = "Connection confirmed in {0} ms.",
        ["Test.Expected"] = "Expected a short confirmation from the configured model.",
        ["Costs.Title"] = "OpenAI costs",
        ["Costs.Subtitle"] = "Standard prices per 1M tokens, local estimates, and optional organization cost data.",
        ["Costs.TodayEstimate"] = "Today estimate",
        ["Costs.MonthEstimate"] = "Month estimate",
        ["Costs.Requests"] = "Requests today",
        ["Costs.Tokens"] = "Tokens today",
        ["Costs.LastSync"] = "Last price sync",
        ["Costs.Models"] = "Models",
        ["Costs.ApiCost"] = "Organization cost",
        ["Costs.Unavailable"] = "Not available",
        ["Costs.Model"] = "Model",
        ["Costs.Input"] = "Input / 1M",
        ["Costs.Cached"] = "Cached / 1M",
        ["Costs.Output"] = "Output / 1M",
        ["Costs.Refreshing"] = "Refreshing OpenAI pricing and cost data...",
        ["Costs.Refreshed"] = "Cost data refreshed.",
        ["Status.Title"] = "Application status",
        ["Status.Thinking"] = "Thinking with the configured model...",
        ["Status.Setup"] = "Setup",
        ["Status.Completed"] = "completed",
        ["Status.Required"] = "required",
        ["Status.Pricing"] = "Pricing cache",
        ["Status.Logs"] = "Logs",
        ["Status.Prompts"] = "YAML prompts",
        ["Help.Title"] = "Command line",
        ["Help.Usage"] = "Usage: PromptMeUp [command] [options]",
        ["Help.Version"] = "Show application and runtime versions.",
        ["Help.Setup"] = "Open first-run / AI setup.",
        ["Help.Status"] = "Show configuration and local service status.",
        ["Help.Query"] = "Send one prompt to the configured model.",
        ["Help.Chat"] = "Open an interactive multi-turn chat.",
        ["Help.Test"] = "Run the YAML connection prompt with teletype output.",
        ["Help.Costs"] = "Refresh and show prices, usage, and monthly costs.",
        ["Help.Language"] = "Override the UI language: it, en, fr, de, es, vi.",
        ["Help.Font"] = "Install JetBrainsMono Nerd Font (opt-in).",
        ["Help.Path"] = "Preview, install, remove, or inspect the portable hm PATH entry.",
        ["Help.ThirdParty"] = "Show direct dependencies and third-party licenses.",
        ["Help.Rendering"] = "Disable animation or emoji for constrained terminals.",
        ["Help.Yes"] = "Preauthorize only an explicit PATH or font operation; never a chat command.",
        ["Help.DryRun"] = "Preview font installation without changing the PC.",
        ["Error.SetupRequired"] = "Run --setup before using AI commands.",
        ["Error.ApiKeyMissing"] = "The environment variable {0} is missing or invalid.",
        ["Error.InteractiveRequired"] = "This command requires an interactive terminal.",
        ["Error.RequestFailed"] = "OpenAI request failed: {0}",
        ["Error.PromptMissing"] = "Prompt resource '{0}' was not found.",
        ["Font.Title"] = "Nerd Font installer",
        ["Font.Confirm"] = "Install JetBrainsMono Nerd Font for the current user?",
        ["Font.Progress"] = "Installing terminal font...",
        ["Font.Ready"] = "Font ready: {0}",
        ["Font.Preview"] = "Dry run complete; no system changes were made.",
        ["Font.TerminalHint"] = "Select the installed Nerd Font in your terminal profile, then reopen the terminal.",
        ["ThirdParty.Title"] = "Third-party software",
        ["ThirdParty.Subtitle"] = "Direct runtime dependencies used by PromptMeUp.",
        ["ThirdParty.Package"] = "Package",
        ["ThirdParty.Version"] = "Version",
        ["ThirdParty.License"] = "License",
        ["ThirdParty.FullNotices"] = "Full notices: THIRD_PARTY_NOTICES.md",
        ["Path.Title"] = "Portable PATH",
        ["Path.Action"] = "Choose a PATH action",
        ["Path.Install"] = "Add this hm folder to the user PATH",
        ["Path.Remove"] = "Remove the managed hm folder from the user PATH",
        ["Path.Status"] = "Inspect PATH status",
        ["Path.Confirm"] = "Apply this exact PATH change?",
        ["Path.Present"] = "This hm folder is already in the persistent user PATH.",
        ["Path.Missing"] = "This hm folder is not in the persistent user PATH.",
        ["Command.Preview"] = "COMMAND PREVIEW // AUTHORIZATION REQUIRED",
        ["Command.Risk"] = "Risk score",
        ["Command.AiReview"] = "AI review",
        ["Command.LocalReview"] = "Local review",
        ["Command.SendOutput"] = "If executed, stdout/stderr may be stored locally and sent to OpenAI in the next turn.",
        ["Command.Authorize"] = "Authorize this exact command now?",
        ["Command.Cancelled"] = "Command cancelled; nothing was executed.",
        ["Command.Output"] = "Command output",
        ["Command.Running"] = "Running the authorized command...",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.Back"] = "Back",
        ["Common.Cancel"] = "Cancel",
        ["Common.Unknown"] = "unknown"
    };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Overrides =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["it"] = Italian(),
            ["fr"] = French(),
            ["de"] = German(),
            ["es"] = Spanish(),
            ["vi"] = Vietnamese()
        };

    public string Language { get; private set; } = "en";

    public CultureInfo Culture => SupportedLanguages.Culture(Language);

    /// <summary>Applies one supported interface language for the current invocation.</summary>
    public void SetLanguage(string language) => Language = SupportedLanguages.Normalize(language);

    /// <summary>Resolves and formats one localized UI string with English as a guarded fallback.</summary>
    public string Text(string key, params object?[] args)
    {
        var template = Overrides.TryGetValue(Language, out var localized) && localized.TryGetValue(key, out var translated)
            ? translated
            : English.TryGetValue(key, out var english)
                ? english
                : key;
        return args.Length == 0 ? template : string.Format(Culture, template, args);
    }

    /// <summary>Builds the complete Italian product-language catalog.</summary>
    private static IReadOnlyDictionary<string, string> Italian() => new Dictionary<string, string>
    {
        ["Tagline"] = "Prompt engineering, conversazioni e controllo costi — organizzati in locale.",
        ["Status.Language"] = "Lingua",
        ["Status.Model"] = "Modello",
        ["Status.ApiKey"] = "Chiave API",
        ["Status.AdminKey"] = "Chiave admin",
        ["Status.Database"] = "Database",
        ["Status.Ready"] = "pronta",
        ["Status.Missing"] = "mancante",
        ["Status.Disabled"] = "disabilitata",
        ["Status.Local"] = "locale",
        ["Footer.Command"] = "Comando",
        ["Footer.Version"] = "Versione",
        ["Footer.Data"] = "Dati",
        ["Setup.Title"] = "CONFIGURAZIONE AI // PMU-SETUP-01",
        ["Setup.Header"] = "CONFIGURAZIONE SISTEMA",
        ["Setup.Subtitle"] = "Configurazione iniziale. I segreti restano nell'ambiente utente Windows.",
        ["Setup.Language"] = "Lingua dell'interfaccia",
        ["Setup.AiEnabled"] = "Abilitare il provider OpenAI?",
        ["Setup.KeyStatus"] = "Stato OPENAI_API_KEY",
        ["Setup.SetKey"] = "Impostare o cambiare OPENAI_API_KEY adesso?",
        ["Setup.KeyPrompt"] = "Chiave API OpenAI",
        ["Setup.AdminKeyStatus"] = "Stato OPENAI_ADMIN_KEY",
        ["Setup.SetAdminKey"] = "Impostare la chiave admin opzionale per i costi organizzazione?",
        ["Setup.AdminKeyPrompt"] = "Chiave admin OpenAI",
        ["Setup.Model"] = "Modello",
        ["Setup.Reasoning"] = "Sforzo di ragionamento",
        ["Setup.Detail"] = "Dettaglio analisi",
        ["Setup.Custom"] = "Istruzione AI aggiuntiva (opzionale)",
        ["Setup.Location"] = "Includere la posizione Windows nelle richieste AI?",
        ["Setup.Endpoint"] = "Endpoint OpenAI Responses",
        ["Setup.CommandReview"] = "Usare la revisione AI opzionale prima di autorizzare i comandi?",
        ["Setup.PromptCaching"] = "Abilitare il prompt caching OpenAI?",
        ["Setup.MemoryLimits"] = "Limiti memoria per sessioni brevi",
        ["Setup.MaxTurns"] = "Numero massimo di turni utente",
        ["Setup.MaxMessage"] = "Caratteri massimi per messaggio",
        ["Setup.MaxContext"] = "Uso massimo context window (%)",
        ["Setup.MaxCommandOutput"] = "Caratteri massimi output comando conservati",
        ["Setup.CommandTimeout"] = "Timeout comando in secondi",
        ["Setup.Test"] = "Verificare ora la connessione AI?",
        ["Setup.Saved"] = "Configurazione salvata.",
        ["Setup.Cancelled"] = "Configurazione annullata; nessuna modifica salvata.",
        ["Setup.Summary"] = "Riepilogo configurazione",
        ["Setup.Confirm"] = "Salvare queste impostazioni?",
        ["Setup.Compact"] = "Compatto · consumo minimo",
        ["Setup.Balanced"] = "Bilanciato",
        ["Setup.Detailed"] = "Dettagliato · budget maggiore",
        ["Model.gpt-5.6-sol"] = "Modello di frontiera per lavoro professionale e ragionamento impegnativi.",
        ["Model.gpt-5.6-terra"] = "Equilibrio tra intelligenza, latenza e costo per il lavoro quotidiano.",
        ["Model.gpt-5.6-luna"] = "Modello conveniente per attività rapide e ad alto volume.",
        ["Model.gpt-5.5"] = "Precedente modello di frontiera per lavori professionali complessi.",
        ["Model.gpt-5.4"] = "Modello accessibile per programmazione e lavoro professionale.",
        ["Model.gpt-5.4-mini"] = "Modello efficiente per attività mirate e ad alto volume.",
        ["Model.gpt-5.4-nano"] = "Modello economico per estrazione, classificazione e attività semplici.",
        ["Reasoning.none"] = "Nessuno",
        ["Reasoning.low"] = "Basso",
        ["Reasoning.medium"] = "Medio",
        ["Reasoning.high"] = "Alto",
        ["Reasoning.xhigh"] = "Molto alto",
        ["Reasoning.max"] = "Massimo",
        ["Main.Title"] = "Centro comandi",
        ["Main.Choose"] = "Scegli un'azione",
        ["Main.Chat"] = "Chat AI interattiva",
        ["Main.Query"] = "Prompt singolo",
        ["Main.Costs"] = "Utilizzo e costi",
        ["Main.Status"] = "Stato applicazione",
        ["Main.Setup"] = "Configurazione AI",
        ["Main.Test"] = "Test connessione AI",
        ["Main.Font"] = "Installa Nerd Font",
        ["Main.Exit"] = "Esci",
        ["Query.Prompt"] = "Inserisci il prompt",
        ["Query.Response"] = "Risposta del modello",
        ["Query.Empty"] = "Il prompt non può essere vuoto.",
        ["Chat.Title"] = "Chat interattiva",
        ["Chat.Hint"] = "Comandi: /run <comando>, /exit, /clear, /costs, /status",
        ["Chat.You"] = "Tu",
        ["Chat.Assistant"] = "PromptMeUp",
        ["Chat.Cleared"] = "Conversazione azzerata.",
        ["Chat.Exit"] = "Chat chiusa.",
        ["Chat.Pruned"] = "Il contesto attivo ha rimosso {0} messaggi precedenti; il registro di audit resta completo.",
        ["Test.Title"] = "Test connessione AI",
        ["Test.Success"] = "Connessione confermata in {0} ms.",
        ["Test.Expected"] = "È attesa una breve conferma dal modello configurato.",
        ["Costs.Title"] = "Costi OpenAI",
        ["Costs.Subtitle"] = "Prezzi standard per 1M token, stime locali e costi organizzazione opzionali.",
        ["Costs.TodayEstimate"] = "Stima oggi",
        ["Costs.MonthEstimate"] = "Stima mese",
        ["Costs.Requests"] = "Richieste oggi",
        ["Costs.Tokens"] = "Token oggi",
        ["Costs.LastSync"] = "Ultima sincronizzazione",
        ["Costs.Models"] = "Modelli",
        ["Costs.ApiCost"] = "Costo organizzazione",
        ["Costs.Unavailable"] = "Non disponibile",
        ["Costs.Model"] = "Modello",
        ["Costs.Input"] = "Input / 1M",
        ["Costs.Cached"] = "Cache / 1M",
        ["Costs.Output"] = "Output / 1M",
        ["Costs.Refreshing"] = "Aggiornamento prezzi e costi OpenAI...",
        ["Costs.Refreshed"] = "Dati di costo aggiornati.",
        ["Status.Title"] = "Stato applicazione",
        ["Status.Thinking"] = "Elaborazione con il modello configurato...",
        ["Status.Setup"] = "Configurazione",
        ["Status.Completed"] = "completata",
        ["Status.Required"] = "richiesta",
        ["Status.Pricing"] = "Cache prezzi",
        ["Status.Logs"] = "Log",
        ["Status.Prompts"] = "Prompt YAML",
        ["Help.Title"] = "Riga di comando",
        ["Help.Usage"] = "Uso: hm [comando] [opzioni]",
        ["Help.Version"] = "Mostra le versioni dell'applicazione e del runtime.",
        ["Help.Setup"] = "Apre la configurazione iniziale / AI.",
        ["Help.Status"] = "Mostra configurazione e servizi locali.",
        ["Help.Query"] = "Invia un singolo prompt al modello configurato.",
        ["Help.Chat"] = "Apre una chat interattiva multi-turno.",
        ["Help.Test"] = "Esegue il prompt YAML di test con effetto teletype.",
        ["Help.Costs"] = "Aggiorna e mostra prezzi, utilizzo e costi mensili.",
        ["Help.Language"] = "Sovrascrive la lingua UI: it, en, fr, de, es, vi.",
        ["Help.Font"] = "Installa JetBrainsMono Nerd Font (opt-in).",
        ["Help.Rendering"] = "Disabilita animazioni o emoji per terminali limitati.",
        ["Help.Yes"] = "Preautorizza solo un'operazione PATH o font esplicita; mai un comando della chat.",
        ["Help.DryRun"] = "Simula l'installazione font senza modificare il PC.",
        ["Help.ThirdParty"] = "Mostra dipendenze dirette e licenze di terze parti.",
        ["ThirdParty.Title"] = "Software di terze parti",
        ["ThirdParty.Subtitle"] = "Dipendenze runtime dirette usate da PromptMeUp.",
        ["ThirdParty.Package"] = "Pacchetto",
        ["ThirdParty.Version"] = "Versione",
        ["ThirdParty.License"] = "Licenza",
        ["ThirdParty.FullNotices"] = "Note complete: THIRD_PARTY_NOTICES.md",
        ["Help.Path"] = "Mostra, aggiunge o rimuove dal PATH la cartella portabile di hm.",
        ["Path.Title"] = "PATH portabile",
        ["Path.Action"] = "Scegli un'azione PATH",
        ["Path.Install"] = "Aggiungi questa cartella hm al PATH utente",
        ["Path.Remove"] = "Rimuovi dal PATH utente la cartella hm gestita",
        ["Path.Status"] = "Controlla lo stato PATH",
        ["Path.Confirm"] = "Applicare esattamente questa modifica al PATH?",
        ["Path.Present"] = "Questa cartella hm è già nel PATH utente persistente.",
        ["Path.Missing"] = "Questa cartella hm non è nel PATH utente persistente.",
        ["Command.Preview"] = "ANTEPRIMA COMANDO // AUTORIZZAZIONE RICHIESTA",
        ["Command.Risk"] = "Punteggio rischio",
        ["Command.AiReview"] = "Revisione AI",
        ["Command.LocalReview"] = "Revisione locale",
        ["Command.SendOutput"] = "Se eseguiti, stdout/stderr possono essere salvati in locale e inviati a OpenAI nel turno successivo.",
        ["Command.Authorize"] = "Autorizzare ora questo comando esatto?",
        ["Command.Cancelled"] = "Comando annullato; non è stato eseguito nulla.",
        ["Command.Output"] = "Output comando",
        ["Command.Running"] = "Esecuzione del comando autorizzato...",
        ["Error.SetupRequired"] = "Esegui --setup prima di usare i comandi AI.",
        ["Error.ApiKeyMissing"] = "La variabile ambiente {0} è mancante o non valida.",
        ["Error.InteractiveRequired"] = "Questo comando richiede un terminale interattivo.",
        ["Error.RequestFailed"] = "Richiesta OpenAI fallita: {0}",
        ["Error.PromptMissing"] = "Risorsa prompt '{0}' non trovata.",
        ["Font.Title"] = "Installer Nerd Font",
        ["Font.Confirm"] = "Installare JetBrainsMono Nerd Font per l'utente corrente?",
        ["Font.Progress"] = "Installazione font terminale...",
        ["Font.Ready"] = "Font pronto: {0}",
        ["Font.Preview"] = "Simulazione completata; nessuna modifica al sistema.",
        ["Font.TerminalHint"] = "Seleziona il Nerd Font installato nel profilo del terminale, poi riapri il terminale.",
        ["Common.Yes"] = "Sì",
        ["Common.No"] = "No",
        ["Common.Back"] = "Indietro",
        ["Common.Cancel"] = "Annulla",
        ["Common.Unknown"] = "sconosciuto"
    };

    /// <summary>Builds the complete French product-language catalog.</summary>
    private static IReadOnlyDictionary<string, string> French() => Complete(CommonRomance(
        "Ingénierie de prompts, conversations et suivi des coûts — organisés localement.", "Langue", "Modèle", "prête", "manquante",
        "Configuration IA", "Activer le fournisseur OpenAI ?", "Effort de raisonnement", "Détail de l'analyse", "Instruction IA supplémentaire (facultatif)",
        "Centre de commandes", "Chat IA interactif", "Coûts OpenAI", "Estimation aujourd'hui", "Estimation du mois", "Requêtes aujourd'hui", "Jetons aujourd'hui",
        "Entrez votre prompt", "Réponse du modèle", "Connexion confirmée en {0} ms.", "Oui", "Non"), FrenchCompletion());

    /// <summary>Builds the complete German product-language catalog.</summary>
    private static IReadOnlyDictionary<string, string> German() => Complete(CommonGerman(), GermanCompletion());

    /// <summary>Builds the complete Spanish product-language catalog.</summary>
    private static IReadOnlyDictionary<string, string> Spanish() => Complete(CommonRomance(
        "Ingeniería de prompts, conversación y control de costes — organizado localmente.", "Idioma", "Modelo", "lista", "ausente",
        "Configuración de IA", "¿Activar el proveedor OpenAI?", "Esfuerzo de razonamiento", "Detalle del análisis", "Instrucción adicional de IA (opcional)",
        "Centro de comandos", "Chat de IA interactivo", "Costes de OpenAI", "Estimación de hoy", "Estimación mensual", "Solicitudes hoy", "Tokens hoy",
        "Escribe tu prompt", "Respuesta del modelo", "Conexión confirmada en {0} ms.", "Sí", "No"), SpanishCompletion());

    /// <summary>Builds the complete Vietnamese product-language catalog.</summary>
    private static IReadOnlyDictionary<string, string> Vietnamese() => Complete(new Dictionary<string, string>
    {
        ["Tagline"] = "Kỹ thuật prompt, hội thoại và theo dõi chi phí — được tổ chức cục bộ.",
        ["Status.Language"] = "Ngôn ngữ",
        ["Status.Model"] = "Mô hình",
        ["Status.ApiKey"] = "Khóa API",
        ["Status.AdminKey"] = "Khóa quản trị",
        ["Status.Database"] = "Cơ sở dữ liệu",
        ["Status.Ready"] = "sẵn sàng",
        ["Status.Missing"] = "thiếu",
        ["Status.Disabled"] = "đã tắt",
        ["Status.Local"] = "cục bộ",
        ["Setup.Title"] = "THIẾT LẬP AI // PMU-SETUP-01",
        ["Setup.Subtitle"] = "Cấu hình lần đầu. Khóa bí mật chỉ nằm trong môi trường người dùng Windows.",
        ["Setup.Language"] = "Ngôn ngữ giao diện",
        ["Setup.AiEnabled"] = "Bật nhà cung cấp OpenAI?",
        ["Setup.SetKey"] = "Đặt hoặc đổi OPENAI_API_KEY ngay bây giờ?",
        ["Setup.KeyPrompt"] = "Khóa API OpenAI",
        ["Setup.SetAdminKey"] = "Đặt khóa quản trị tùy chọn để đọc chi phí tổ chức?",
        ["Setup.AdminKeyPrompt"] = "Khóa quản trị OpenAI",
        ["Setup.Model"] = "Mô hình",
        ["Setup.Reasoning"] = "Mức suy luận",
        ["Setup.Detail"] = "Mức chi tiết",
        ["Setup.Custom"] = "Chỉ dẫn AI bổ sung (tùy chọn)",
        ["Setup.Location"] = "Gửi vị trí Windows trong yêu cầu AI?",
        ["Setup.Test"] = "Kiểm tra kết nối AI ngay?",
        ["Setup.Saved"] = "Đã lưu cấu hình.",
        ["Setup.Summary"] = "Tóm tắt cấu hình",
        ["Setup.Confirm"] = "Lưu các cài đặt này?",
        ["Setup.Compact"] = "Gọn · ít token nhất",
        ["Setup.Balanced"] = "Cân bằng",
        ["Setup.Detailed"] = "Chi tiết · ngân sách lớn hơn",
        ["Model.gpt-5.6-sol"] = "Mô hình hàng đầu cho công việc chuyên môn và suy luận phức tạp.",
        ["Model.gpt-5.6-terra"] = "Cân bằng trí tuệ, độ trễ và chi phí cho công việc hằng ngày.",
        ["Model.gpt-5.6-luna"] = "Mô hình tiết kiệm cho khối lượng công việc lớn và cần tốc độ.",
        ["Model.gpt-5.5"] = "Mô hình hàng đầu thế hệ trước cho công việc chuyên môn phức tạp.",
        ["Model.gpt-5.4"] = "Mô hình có chi phí hợp lý cho lập trình và công việc chuyên môn.",
        ["Model.gpt-5.4-mini"] = "Mô hình hiệu quả cho tác vụ tập trung và khối lượng lớn.",
        ["Model.gpt-5.4-nano"] = "Mô hình chi phí thấp cho trích xuất, xếp hạng và tác vụ đơn giản.",
        ["Reasoning.none"] = "Không",
        ["Reasoning.low"] = "Thấp",
        ["Reasoning.medium"] = "Trung bình",
        ["Reasoning.high"] = "Cao",
        ["Reasoning.xhigh"] = "Rất cao",
        ["Reasoning.max"] = "Tối đa",
        ["Main.Title"] = "Trung tâm lệnh",
        ["Main.Choose"] = "Chọn tác vụ",
        ["Main.Chat"] = "Chat AI tương tác",
        ["Main.Query"] = "Prompt đơn",
        ["Main.Costs"] = "Sử dụng và chi phí",
        ["Main.Status"] = "Trạng thái ứng dụng",
        ["Main.Setup"] = "Thiết lập AI",
        ["Main.Test"] = "Kiểm tra kết nối AI",
        ["Main.Font"] = "Cài Nerd Font",
        ["Main.Exit"] = "Thoát",
        ["Query.Prompt"] = "Nhập prompt",
        ["Query.Response"] = "Phản hồi của mô hình",
        ["Chat.Title"] = "Chat tương tác",
        ["Chat.Hint"] = "Lệnh: /exit, /clear, /costs, /status",
        ["Chat.You"] = "Bạn",
        ["Chat.Cleared"] = "Đã xóa hội thoại.",
        ["Chat.Exit"] = "Đã đóng chat.",
        ["Test.Title"] = "Kiểm tra kết nối AI",
        ["Test.Success"] = "Kết nối thành công trong {0} ms.",
        ["Costs.Title"] = "Chi phí OpenAI",
        ["Costs.Subtitle"] = "Giá chuẩn trên 1 triệu token, ước tính cục bộ và chi phí tổ chức tùy chọn.",
        ["Costs.TodayEstimate"] = "Ước tính hôm nay",
        ["Costs.MonthEstimate"] = "Ước tính tháng",
        ["Costs.Requests"] = "Yêu cầu hôm nay",
        ["Costs.Tokens"] = "Token hôm nay",
        ["Costs.LastSync"] = "Đồng bộ giá gần nhất",
        ["Costs.Models"] = "Mô hình",
        ["Costs.ApiCost"] = "Chi phí tổ chức",
        ["Costs.Unavailable"] = "Không có",
        ["Costs.Model"] = "Mô hình",
        ["Costs.Input"] = "Đầu vào / 1M",
        ["Costs.Cached"] = "Đã lưu / 1M",
        ["Costs.Output"] = "Đầu ra / 1M",
        ["Costs.Refreshing"] = "Đang cập nhật giá và chi phí OpenAI...",
        ["Error.SetupRequired"] = "Hãy chạy --setup trước khi dùng lệnh AI.",
        ["Error.ApiKeyMissing"] = "Biến môi trường {0} bị thiếu hoặc không hợp lệ.",
        ["Error.InteractiveRequired"] = "Lệnh này cần terminal tương tác.",
        ["Error.RequestFailed"] = "Yêu cầu OpenAI thất bại: {0}",
        ["Font.Title"] = "Trình cài Nerd Font",
        ["Font.Confirm"] = "Cài JetBrainsMono Nerd Font cho người dùng hiện tại?",
        ["Font.Progress"] = "Đang cài font terminal...",
        ["Font.Ready"] = "Font đã sẵn sàng: {0}",
        ["Font.Preview"] = "Đã mô phỏng; không thay đổi hệ thống.",
        ["Font.TerminalHint"] = "Chọn Nerd Font trong hồ sơ terminal rồi mở lại terminal.",
        ["Common.Yes"] = "Có",
        ["Common.No"] = "Không",
        ["Common.Cancel"] = "Hủy",
        ["Common.Unknown"] = "không rõ"
    }, VietnameseCompletion());

    /// <summary>Builds the shared French-first Romance-language baseline.</summary>
    private static IReadOnlyDictionary<string, string> CommonRomance(
        string tagline, string language, string model, string ready, string missing,
        string setup, string enableAi, string reasoning, string detail, string custom,
        string commandCenter, string chat, string costs, string today, string month, string requests, string tokens,
        string prompt, string response, string connection, string yes, string no) => new Dictionary<string, string>
        {
            ["Tagline"] = tagline,
            ["Status.Language"] = language,
            ["Status.Model"] = model,
            ["Status.ApiKey"] = "Clé API",
            ["Status.AdminKey"] = "Clé admin",
            ["Status.Database"] = "Base de données",
            ["Status.Ready"] = ready,
            ["Status.Missing"] = missing,
            ["Status.Disabled"] = "désactivée",
            ["Status.Local"] = "locale",
            ["Setup.Title"] = setup.ToUpperInvariant() + " // PMU-SETUP-01",
            ["Setup.Subtitle"] = "Configuration initiale. Les secrets restent dans l'environnement utilisateur Windows.",
            ["Setup.Language"] = language,
            ["Setup.AiEnabled"] = enableAi,
            ["Setup.SetKey"] = "Configurer ou modifier OPENAI_API_KEY maintenant ?",
            ["Setup.KeyPrompt"] = "Clé API OpenAI",
            ["Setup.SetAdminKey"] = "Configurer la clé admin facultative pour les coûts d'organisation ?",
            ["Setup.AdminKeyPrompt"] = "Clé admin OpenAI",
            ["Setup.Model"] = model,
            ["Setup.Reasoning"] = reasoning,
            ["Setup.Detail"] = detail,
            ["Setup.Custom"] = custom,
            ["Setup.Location"] = "Inclure la localisation Windows dans les requêtes IA ?",
            ["Setup.Test"] = "Tester la connexion IA maintenant ?",
            ["Setup.Saved"] = "Configuration enregistrée.",
            ["Setup.Summary"] = "Résumé de configuration",
            ["Setup.Confirm"] = "Enregistrer ces paramètres ?",
            ["Setup.Compact"] = "Compact · utilisation minimale",
            ["Setup.Balanced"] = "Équilibré",
            ["Setup.Detailed"] = "Détaillé · budget supérieur",
            ["Reasoning.none"] = "Aucun",
            ["Reasoning.low"] = "Faible",
            ["Reasoning.medium"] = "Moyen",
            ["Reasoning.high"] = "Élevé",
            ["Reasoning.xhigh"] = "Très élevé",
            ["Reasoning.max"] = "Maximum",
            ["Main.Title"] = commandCenter,
            ["Main.Choose"] = "Choisissez une action",
            ["Main.Chat"] = chat,
            ["Main.Query"] = "Prompt unique",
            ["Main.Costs"] = costs,
            ["Main.Status"] = "État de l'application",
            ["Main.Setup"] = setup,
            ["Main.Test"] = "Tester la connexion IA",
            ["Main.Font"] = "Installer Nerd Font",
            ["Main.Exit"] = "Quitter",
            ["Query.Prompt"] = prompt,
            ["Query.Response"] = response,
            ["Chat.Title"] = chat,
            ["Chat.Hint"] = "Commandes : /exit, /clear, /costs, /status",
            ["Chat.You"] = language == "Idioma" ? "Tú" : "Vous",
            ["Chat.Cleared"] = "Conversation effacée.",
            ["Chat.Exit"] = "Chat fermé.",
            ["Test.Title"] = "Test de connexion IA",
            ["Test.Success"] = connection,
            ["Costs.Title"] = costs,
            ["Costs.Subtitle"] = "Prix standard par million de jetons, estimations locales et coûts d'organisation facultatifs.",
            ["Costs.TodayEstimate"] = today,
            ["Costs.MonthEstimate"] = month,
            ["Costs.Requests"] = requests,
            ["Costs.Tokens"] = tokens,
            ["Costs.LastSync"] = "Dernière synchronisation",
            ["Costs.Models"] = model,
            ["Costs.ApiCost"] = "Coût organisation",
            ["Costs.Unavailable"] = "Indisponible",
            ["Costs.Model"] = model,
            ["Costs.Input"] = "Entrée / 1M",
            ["Costs.Cached"] = "Cache / 1M",
            ["Costs.Output"] = "Sortie / 1M",
            ["Costs.Refreshing"] = "Actualisation des prix et coûts OpenAI...",
            ["Error.SetupRequired"] = "Exécutez --setup avant les commandes IA.",
            ["Error.ApiKeyMissing"] = "La variable d'environnement {0} est absente ou invalide.",
            ["Error.InteractiveRequired"] = "Cette commande nécessite un terminal interactif.",
            ["Error.RequestFailed"] = "La requête OpenAI a échoué : {0}",
            ["Font.Title"] = "Installation Nerd Font",
            ["Font.Confirm"] = "Installer JetBrainsMono Nerd Font pour l'utilisateur actuel ?",
            ["Font.Progress"] = "Installation de la police terminal...",
            ["Font.Ready"] = "Police prête : {0}",
            ["Font.Preview"] = "Simulation terminée ; aucune modification système.",
            ["Font.TerminalHint"] = "Sélectionnez la Nerd Font dans le profil du terminal puis rouvrez-le.",
            ["Common.Yes"] = yes,
            ["Common.No"] = no,
            ["Common.Cancel"] = "Annuler",
            ["Common.Unknown"] = "inconnu"
        };

    /// <summary>Builds the established German baseline before newer surfaces are merged.</summary>
    private static IReadOnlyDictionary<string, string> CommonGerman() => new Dictionary<string, string>
    {
        ["Tagline"] = "Prompt-Engineering, Gespräche und Kostenkontrolle — lokal organisiert.",
        ["Status.Language"] = "Sprache",
        ["Status.Model"] = "Modell",
        ["Status.ApiKey"] = "API-Schlüssel",
        ["Status.AdminKey"] = "Admin-Schlüssel",
        ["Status.Database"] = "Datenbank",
        ["Status.Ready"] = "bereit",
        ["Status.Missing"] = "fehlt",
        ["Status.Disabled"] = "deaktiviert",
        ["Status.Local"] = "lokal",
        ["Setup.Title"] = "KI-EINRICHTUNG // PMU-SETUP-01",
        ["Setup.Subtitle"] = "Erstkonfiguration. Geheimnisse bleiben in der Windows-Benutzerumgebung.",
        ["Setup.Language"] = "Oberflächensprache",
        ["Setup.AiEnabled"] = "OpenAI-Anbieter aktivieren?",
        ["Setup.SetKey"] = "OPENAI_API_KEY jetzt setzen oder ändern?",
        ["Setup.KeyPrompt"] = "OpenAI API-Schlüssel",
        ["Setup.SetAdminKey"] = "Optionalen Admin-Schlüssel für Organisationskosten setzen?",
        ["Setup.AdminKeyPrompt"] = "OpenAI Admin-Schlüssel",
        ["Setup.Model"] = "Modell",
        ["Setup.Reasoning"] = "Denkaufwand",
        ["Setup.Detail"] = "Analysedetail",
        ["Setup.Custom"] = "Zusätzliche KI-Anweisung (optional)",
        ["Setup.Location"] = "Windows-Standort in KI-Anfragen einbeziehen?",
        ["Setup.Test"] = "KI-Verbindung jetzt testen?",
        ["Setup.Saved"] = "Konfiguration gespeichert.",
        ["Setup.Summary"] = "Konfigurationsübersicht",
        ["Setup.Confirm"] = "Diese Einstellungen speichern?",
        ["Setup.Compact"] = "Kompakt · geringste Nutzung",
        ["Setup.Balanced"] = "Ausgewogen",
        ["Setup.Detailed"] = "Detailliert · größeres Budget",
        ["Reasoning.none"] = "Keine",
        ["Reasoning.low"] = "Niedrig",
        ["Reasoning.medium"] = "Mittel",
        ["Reasoning.high"] = "Hoch",
        ["Reasoning.xhigh"] = "Sehr hoch",
        ["Reasoning.max"] = "Maximum",
        ["Main.Title"] = "Kommandozentrale",
        ["Main.Choose"] = "Aktion auswählen",
        ["Main.Chat"] = "Interaktiver KI-Chat",
        ["Main.Query"] = "Einzelner Prompt",
        ["Main.Costs"] = "Nutzung und Kosten",
        ["Main.Status"] = "Anwendungsstatus",
        ["Main.Setup"] = "KI-Einrichtung",
        ["Main.Test"] = "KI-Verbindung testen",
        ["Main.Font"] = "Nerd Font installieren",
        ["Main.Exit"] = "Beenden",
        ["Query.Prompt"] = "Prompt eingeben",
        ["Query.Response"] = "Modellantwort",
        ["Chat.Title"] = "Interaktiver Chat",
        ["Chat.Hint"] = "Befehle: /exit, /clear, /costs, /status",
        ["Chat.You"] = "Sie",
        ["Chat.Cleared"] = "Gespräch gelöscht.",
        ["Chat.Exit"] = "Chat geschlossen.",
        ["Test.Title"] = "KI-Verbindungstest",
        ["Test.Success"] = "Verbindung in {0} ms bestätigt.",
        ["Costs.Title"] = "OpenAI-Kosten",
        ["Costs.Subtitle"] = "Standardpreise pro 1 Mio. Token, lokale Schätzungen und optionale Organisationskosten.",
        ["Costs.TodayEstimate"] = "Schätzung heute",
        ["Costs.MonthEstimate"] = "Monatsschätzung",
        ["Costs.Requests"] = "Anfragen heute",
        ["Costs.Tokens"] = "Token heute",
        ["Costs.LastSync"] = "Letzte Preissynchronisierung",
        ["Costs.Models"] = "Modelle",
        ["Costs.ApiCost"] = "Organisationskosten",
        ["Costs.Unavailable"] = "Nicht verfügbar",
        ["Costs.Model"] = "Modell",
        ["Costs.Input"] = "Eingabe / 1M",
        ["Costs.Cached"] = "Cache / 1M",
        ["Costs.Output"] = "Ausgabe / 1M",
        ["Costs.Refreshing"] = "OpenAI-Preise und Kosten werden aktualisiert...",
        ["Error.SetupRequired"] = "Vor KI-Befehlen --setup ausführen.",
        ["Error.ApiKeyMissing"] = "Die Umgebungsvariable {0} fehlt oder ist ungültig.",
        ["Error.InteractiveRequired"] = "Dieser Befehl benötigt ein interaktives Terminal.",
        ["Error.RequestFailed"] = "OpenAI-Anfrage fehlgeschlagen: {0}",
        ["Font.Title"] = "Nerd-Font-Installer",
        ["Font.Confirm"] = "JetBrainsMono Nerd Font für den aktuellen Benutzer installieren?",
        ["Font.Progress"] = "Terminal-Schrift wird installiert...",
        ["Font.Ready"] = "Schrift bereit: {0}",
        ["Font.Preview"] = "Simulation beendet; keine Systemänderung.",
        ["Font.TerminalHint"] = "Die installierte Nerd Font im Terminalprofil auswählen und das Terminal neu öffnen.",
        ["Common.Yes"] = "Ja",
        ["Common.No"] = "Nein",
        ["Common.Cancel"] = "Abbrechen",
        ["Common.Unknown"] = "unbekannt"
    };

    /// <summary>Returns translations for newer French setup, safety, help, and portable-runtime surfaces.</summary>
    private static IReadOnlyDictionary<string, string> FrenchCompletion() => new Dictionary<string, string>
    {
        ["Footer.Command"] = "Commande",
        ["Footer.Version"] = "Version",
        ["Footer.Data"] = "Données",
        ["Setup.Header"] = "CONFIGURATION SYSTÈME",
        ["Setup.KeyStatus"] = "État de OPENAI_API_KEY",
        ["Setup.AdminKeyStatus"] = "État de OPENAI_ADMIN_KEY",
        ["Setup.Cancelled"] = "Configuration annulée ; aucune modification enregistrée.",
        ["Setup.CommandReview"] = "Utiliser l'analyse IA facultative avant d'autoriser les commandes ?",
        ["Setup.PromptCaching"] = "Activer la mise en cache des prompts OpenAI ?",
        ["Setup.MemoryLimits"] = "Limites de mémoire des sessions courtes",
        ["Setup.MaxTurns"] = "Nombre maximal de tours utilisateur",
        ["Setup.MaxMessage"] = "Nombre maximal de caractères par message",
        ["Setup.MaxContext"] = "Utilisation maximale de la fenêtre de contexte (%)",
        ["Setup.MaxCommandOutput"] = "Caractères maximaux de sortie de commande conservés",
        ["Setup.CommandTimeout"] = "Délai d'expiration des commandes en secondes",
        ["Setup.Endpoint"] = "Point de terminaison OpenAI Responses",
        ["Model.gpt-5.6-sol"] = "Modèle de pointe pour les travaux professionnels et raisonnements exigeants.",
        ["Model.gpt-5.6-terra"] = "Équilibre entre intelligence, latence et coût pour le travail quotidien.",
        ["Model.gpt-5.6-luna"] = "Modèle économique pour les charges rapides et volumineuses.",
        ["Model.gpt-5.5"] = "Modèle de pointe précédent pour les travaux professionnels complexes.",
        ["Model.gpt-5.4"] = "Modèle abordable pour le développement et le travail professionnel.",
        ["Model.gpt-5.4-mini"] = "Modèle efficace pour les tâches ciblées et volumineuses.",
        ["Model.gpt-5.4-nano"] = "Modèle économique pour l'extraction, le classement et les tâches simples.",
        ["Query.Empty"] = "Le prompt ne peut pas être vide.",
        ["Chat.Assistant"] = "PromptMeUp",
        ["Chat.Hint"] = "Commandes : /run <commande>, /exit, /clear, /costs, /status",
        ["Chat.Pruned"] = "Le contexte actif a retiré {0} ancien(s) message(s) ; le journal d'audit reste complet.",
        ["Test.Expected"] = "Une courte confirmation du modèle configuré est attendue.",
        ["Costs.Refreshed"] = "Données de coût actualisées.",
        ["Status.Title"] = "État de l'application",
        ["Status.Thinking"] = "Réflexion avec le modèle configuré...",
        ["Status.Setup"] = "Configuration",
        ["Status.Completed"] = "terminée",
        ["Status.Required"] = "requise",
        ["Status.Pricing"] = "Cache des prix",
        ["Status.Logs"] = "Journaux",
        ["Status.Prompts"] = "Prompts YAML",
        ["Help.Title"] = "Ligne de commande",
        ["Help.Usage"] = "Utilisation : hm [commande] [options]",
        ["Help.Version"] = "Affiche les versions de l'application et du runtime.",
        ["Help.Setup"] = "Ouvre la configuration initiale et IA.",
        ["Help.Status"] = "Affiche la configuration et les services locaux.",
        ["Help.Query"] = "Envoie un prompt unique au modèle configuré.",
        ["Help.Chat"] = "Ouvre un chat interactif à plusieurs tours.",
        ["Help.Test"] = "Exécute le prompt YAML de connexion avec effet téléscripteur.",
        ["Help.Costs"] = "Actualise et affiche les prix, l'utilisation et les coûts mensuels.",
        ["Help.Language"] = "Remplace la langue de l'interface : it, en, fr, de, es, vi.",
        ["Help.Font"] = "Installe JetBrainsMono Nerd Font avec consentement.",
        ["Help.Path"] = "Prévisualise, ajoute, retire ou vérifie le dossier portable hm dans PATH.",
        ["Help.ThirdParty"] = "Affiche les dépendances directes et les licences tierces.",
        ["Help.Rendering"] = "Désactive les animations ou les emoji pour les terminaux limités.",
        ["Help.Yes"] = "Préautorise uniquement une opération PATH ou police explicite, jamais une commande de chat.",
        ["Help.DryRun"] = "Simule l'installation de la police sans modifier le système.",
        ["Error.PromptMissing"] = "La ressource de prompt '{0}' est introuvable.",
        ["ThirdParty.Title"] = "Logiciels tiers",
        ["ThirdParty.Subtitle"] = "Dépendances d'exécution directes utilisées par PromptMeUp.",
        ["ThirdParty.Package"] = "Paquet",
        ["ThirdParty.Version"] = "Version",
        ["ThirdParty.License"] = "Licence",
        ["ThirdParty.FullNotices"] = "Mentions complètes : THIRD_PARTY_NOTICES.md",
        ["Path.Title"] = "PATH portable",
        ["Path.Action"] = "Choisissez une action PATH",
        ["Path.Install"] = "Ajouter ce dossier hm au PATH utilisateur",
        ["Path.Remove"] = "Retirer du PATH utilisateur le dossier hm géré",
        ["Path.Status"] = "Vérifier l'état du PATH",
        ["Path.Confirm"] = "Appliquer exactement cette modification du PATH ?",
        ["Path.Present"] = "Ce dossier hm est déjà dans le PATH utilisateur persistant.",
        ["Path.Missing"] = "Ce dossier hm n'est pas dans le PATH utilisateur persistant.",
        ["Command.Preview"] = "APERÇU DE LA COMMANDE // AUTORISATION REQUISE",
        ["Command.Risk"] = "Score de risque",
        ["Command.AiReview"] = "Analyse IA",
        ["Command.LocalReview"] = "Analyse locale",
        ["Command.SendOutput"] = "En cas d'exécution, stdout/stderr peuvent être enregistrés localement et envoyés à OpenAI au tour suivant.",
        ["Command.Authorize"] = "Autoriser cette commande exacte maintenant ?",
        ["Command.Cancelled"] = "Commande annulée ; rien n'a été exécuté.",
        ["Command.Output"] = "Sortie de commande",
        ["Command.Running"] = "Exécution de la commande autorisée...",
        ["Common.Back"] = "Retour"
    };

    /// <summary>Returns complete Spanish translations and replaces French baseline wording.</summary>
    private static IReadOnlyDictionary<string, string> SpanishCompletion() => new Dictionary<string, string>
    {
        ["Status.ApiKey"] = "Clave API",
        ["Status.AdminKey"] = "Clave de administrador",
        ["Status.Database"] = "Base de datos",
        ["Status.Disabled"] = "desactivada",
        ["Status.Local"] = "local",
        ["Footer.Command"] = "Comando",
        ["Footer.Version"] = "Versión",
        ["Footer.Data"] = "Datos",
        ["Setup.Header"] = "CONFIGURACIÓN DEL SISTEMA",
        ["Setup.Subtitle"] = "Configuración inicial. Los secretos permanecen en el entorno de usuario de Windows.",
        ["Setup.KeyStatus"] = "Estado de OPENAI_API_KEY",
        ["Setup.SetKey"] = "¿Configurar o cambiar OPENAI_API_KEY ahora?",
        ["Setup.KeyPrompt"] = "Clave API de OpenAI",
        ["Setup.AdminKeyStatus"] = "Estado de OPENAI_ADMIN_KEY",
        ["Setup.SetAdminKey"] = "¿Configurar la clave de administrador opcional para los costes de organización?",
        ["Setup.AdminKeyPrompt"] = "Clave de administrador de OpenAI",
        ["Setup.Location"] = "¿Incluir la ubicación de Windows en las solicitudes de IA?",
        ["Setup.CommandReview"] = "¿Usar la revisión de IA opcional antes de autorizar comandos?",
        ["Setup.PromptCaching"] = "¿Activar la caché de prompts de OpenAI?",
        ["Setup.MemoryLimits"] = "Límites de memoria para sesiones cortas",
        ["Setup.MaxTurns"] = "Máximo de turnos del usuario",
        ["Setup.MaxMessage"] = "Máximo de caracteres por mensaje",
        ["Setup.MaxContext"] = "Uso máximo de la ventana de contexto (%)",
        ["Setup.MaxCommandOutput"] = "Máximo de caracteres de salida de comando conservados",
        ["Setup.CommandTimeout"] = "Tiempo de espera del comando en segundos",
        ["Setup.Endpoint"] = "Endpoint de OpenAI Responses",
        ["Setup.Test"] = "¿Probar ahora la conexión de IA?",
        ["Setup.Saved"] = "Configuración guardada.",
        ["Setup.Cancelled"] = "Configuración cancelada; no se guardaron cambios.",
        ["Setup.Summary"] = "Resumen de configuración",
        ["Setup.Confirm"] = "¿Guardar esta configuración?",
        ["Setup.Compact"] = "Compacto · uso mínimo",
        ["Setup.Balanced"] = "Equilibrado",
        ["Setup.Detailed"] = "Detallado · presupuesto mayor",
        ["Model.gpt-5.6-sol"] = "Modelo de vanguardia para trabajo profesional y razonamiento exigentes.",
        ["Model.gpt-5.6-terra"] = "Equilibrio entre inteligencia, latencia y coste para el trabajo diario.",
        ["Model.gpt-5.6-luna"] = "Modelo económico para cargas rápidas y de gran volumen.",
        ["Model.gpt-5.5"] = "Modelo de vanguardia anterior para trabajos profesionales complejos.",
        ["Model.gpt-5.4"] = "Modelo asequible para programación y trabajo profesional.",
        ["Model.gpt-5.4-mini"] = "Modelo eficiente para tareas específicas y de gran volumen.",
        ["Model.gpt-5.4-nano"] = "Modelo económico para extracción, clasificación y tareas sencillas.",
        ["Reasoning.none"] = "Ninguno",
        ["Reasoning.low"] = "Bajo",
        ["Reasoning.medium"] = "Medio",
        ["Reasoning.high"] = "Alto",
        ["Reasoning.xhigh"] = "Muy alto",
        ["Reasoning.max"] = "Máximo",
        ["Main.Choose"] = "Elige una acción",
        ["Main.Query"] = "Prompt único",
        ["Main.Status"] = "Estado de la aplicación",
        ["Main.Setup"] = "Configuración de IA",
        ["Main.Test"] = "Probar conexión de IA",
        ["Main.Font"] = "Instalar Nerd Font",
        ["Main.Exit"] = "Salir",
        ["Query.Empty"] = "El prompt no puede estar vacío.",
        ["Chat.Title"] = "Chat de IA interactivo",
        ["Chat.Hint"] = "Comandos: /run <comando>, /exit, /clear, /costs, /status",
        ["Chat.You"] = "Tú",
        ["Chat.Assistant"] = "PromptMeUp",
        ["Chat.Cleared"] = "Conversación borrada.",
        ["Chat.Exit"] = "Chat cerrado.",
        ["Chat.Pruned"] = "El contexto activo eliminó {0} mensaje(s) anterior(es); el registro de auditoría sigue completo.",
        ["Test.Title"] = "Prueba de conexión de IA",
        ["Test.Expected"] = "Se espera una confirmación breve del modelo configurado.",
        ["Costs.Subtitle"] = "Precios estándar por 1 millón de tokens, estimaciones locales y costes de organización opcionales.",
        ["Costs.LastSync"] = "Última sincronización",
        ["Costs.Models"] = "Modelos",
        ["Costs.ApiCost"] = "Coste de organización",
        ["Costs.Unavailable"] = "No disponible",
        ["Costs.Input"] = "Entrada / 1M",
        ["Costs.Cached"] = "Caché / 1M",
        ["Costs.Output"] = "Salida / 1M",
        ["Costs.Refreshing"] = "Actualizando precios y costes de OpenAI...",
        ["Costs.Refreshed"] = "Datos de costes actualizados.",
        ["Status.Title"] = "Estado de la aplicación",
        ["Status.Thinking"] = "Procesando con el modelo configurado...",
        ["Status.Setup"] = "Configuración",
        ["Status.Completed"] = "completada",
        ["Status.Required"] = "requerida",
        ["Status.Pricing"] = "Caché de precios",
        ["Status.Logs"] = "Registros",
        ["Status.Prompts"] = "Prompts YAML",
        ["Help.Title"] = "Línea de comandos",
        ["Help.Usage"] = "Uso: hm [comando] [opciones]",
        ["Help.Version"] = "Muestra las versiones de la aplicación y del runtime.",
        ["Help.Setup"] = "Abre la configuración inicial y de IA.",
        ["Help.Status"] = "Muestra la configuración y los servicios locales.",
        ["Help.Query"] = "Envía un prompt único al modelo configurado.",
        ["Help.Chat"] = "Abre un chat interactivo de varios turnos.",
        ["Help.Test"] = "Ejecuta el prompt YAML de conexión con efecto teletipo.",
        ["Help.Costs"] = "Actualiza y muestra precios, uso y costes mensuales.",
        ["Help.Language"] = "Cambia el idioma de la interfaz: it, en, fr, de, es, vi.",
        ["Help.Font"] = "Instala JetBrainsMono Nerd Font con autorización.",
        ["Help.Path"] = "Previsualiza, añade, elimina o comprueba la carpeta portátil hm en PATH.",
        ["Help.ThirdParty"] = "Muestra dependencias directas y licencias de terceros.",
        ["Help.Rendering"] = "Desactiva animaciones o emoji para terminales limitados.",
        ["Help.Yes"] = "Preautoriza solo una operación PATH o fuente explícita; nunca un comando del chat.",
        ["Help.DryRun"] = "Simula la instalación de la fuente sin cambiar el sistema.",
        ["Error.SetupRequired"] = "Ejecuta --setup antes de usar comandos de IA.",
        ["Error.ApiKeyMissing"] = "La variable de entorno {0} falta o no es válida.",
        ["Error.InteractiveRequired"] = "Este comando requiere un terminal interactivo.",
        ["Error.RequestFailed"] = "La solicitud de OpenAI falló: {0}",
        ["Error.PromptMissing"] = "No se encontró el recurso de prompt '{0}'.",
        ["Font.Title"] = "Instalador de Nerd Font",
        ["Font.Confirm"] = "¿Instalar JetBrainsMono Nerd Font para el usuario actual?",
        ["Font.Progress"] = "Instalando fuente del terminal...",
        ["Font.Ready"] = "Fuente lista: {0}",
        ["Font.Preview"] = "Simulación completada; no se cambió el sistema.",
        ["Font.TerminalHint"] = "Selecciona la Nerd Font instalada en el perfil del terminal y vuelve a abrirlo.",
        ["ThirdParty.Title"] = "Software de terceros",
        ["ThirdParty.Subtitle"] = "Dependencias directas de ejecución usadas por PromptMeUp.",
        ["ThirdParty.Package"] = "Paquete",
        ["ThirdParty.Version"] = "Versión",
        ["ThirdParty.License"] = "Licencia",
        ["ThirdParty.FullNotices"] = "Avisos completos: THIRD_PARTY_NOTICES.md",
        ["Path.Title"] = "PATH portátil",
        ["Path.Action"] = "Elige una acción de PATH",
        ["Path.Install"] = "Añadir esta carpeta hm al PATH del usuario",
        ["Path.Remove"] = "Eliminar del PATH del usuario la carpeta hm gestionada",
        ["Path.Status"] = "Comprobar el estado de PATH",
        ["Path.Confirm"] = "¿Aplicar exactamente este cambio de PATH?",
        ["Path.Present"] = "Esta carpeta hm ya está en el PATH persistente del usuario.",
        ["Path.Missing"] = "Esta carpeta hm no está en el PATH persistente del usuario.",
        ["Command.Preview"] = "VISTA PREVIA DEL COMANDO // AUTORIZACIÓN REQUERIDA",
        ["Command.Risk"] = "Puntuación de riesgo",
        ["Command.AiReview"] = "Revisión de IA",
        ["Command.LocalReview"] = "Revisión local",
        ["Command.SendOutput"] = "Si se ejecuta, stdout/stderr puede guardarse localmente y enviarse a OpenAI en el siguiente turno.",
        ["Command.Authorize"] = "¿Autorizar ahora este comando exacto?",
        ["Command.Cancelled"] = "Comando cancelado; no se ejecutó nada.",
        ["Command.Output"] = "Salida del comando",
        ["Command.Running"] = "Ejecutando el comando autorizado...",
        ["Common.Back"] = "Atrás",
        ["Common.Cancel"] = "Cancelar",
        ["Common.Unknown"] = "desconocido"
    };

    /// <summary>Returns translations for newer German setup, safety, help, and portable-runtime surfaces.</summary>
    private static IReadOnlyDictionary<string, string> GermanCompletion() => new Dictionary<string, string>
    {
        ["Footer.Command"] = "Befehl",
        ["Footer.Version"] = "Version",
        ["Footer.Data"] = "Daten",
        ["Setup.Header"] = "SYSTEMKONFIGURATION",
        ["Setup.KeyStatus"] = "Status von OPENAI_API_KEY",
        ["Setup.AdminKeyStatus"] = "Status von OPENAI_ADMIN_KEY",
        ["Setup.Cancelled"] = "Einrichtung abgebrochen; keine Änderungen gespeichert.",
        ["Setup.CommandReview"] = "Optionale KI-Prüfung vor der Befehlsfreigabe verwenden?",
        ["Setup.PromptCaching"] = "OpenAI-Prompt-Caching aktivieren?",
        ["Setup.MemoryLimits"] = "Speichergrenzen für kurze Sitzungen",
        ["Setup.MaxTurns"] = "Maximale Benutzerrunden",
        ["Setup.MaxMessage"] = "Maximale Zeichen pro Nachricht",
        ["Setup.MaxContext"] = "Maximale Nutzung des Kontextfensters (%)",
        ["Setup.MaxCommandOutput"] = "Maximal gespeicherte Zeichen der Befehlsausgabe",
        ["Setup.CommandTimeout"] = "Befehlszeitlimit in Sekunden",
        ["Setup.Endpoint"] = "OpenAI-Responses-Endpunkt",
        ["Model.gpt-5.6-sol"] = "Spitzenmodell für anspruchsvolle professionelle Arbeit und Schlussfolgerungen.",
        ["Model.gpt-5.6-terra"] = "Ausgewogenes Verhältnis von Intelligenz, Latenz und Kosten im Alltag.",
        ["Model.gpt-5.6-luna"] = "Kostenbewusstes Modell für schnelle Aufgaben mit hohem Volumen.",
        ["Model.gpt-5.5"] = "Vorheriges Spitzenmodell für komplexe professionelle Arbeit.",
        ["Model.gpt-5.4"] = "Preiswertes Modell für Programmierung und professionelle Arbeit.",
        ["Model.gpt-5.4-mini"] = "Effizientes Modell für fokussierte Aufgaben mit hohem Volumen.",
        ["Model.gpt-5.4-nano"] = "Kostengünstiges Modell für Extraktion, Rangfolge und einfache Aufgaben.",
        ["Query.Empty"] = "Der Prompt darf nicht leer sein.",
        ["Chat.Assistant"] = "PromptMeUp",
        ["Chat.Hint"] = "Befehle: /run <Befehl>, /exit, /clear, /costs, /status",
        ["Chat.Pruned"] = "Der aktive Kontext hat {0} ältere Nachricht(en) entfernt; das Audit-Protokoll bleibt vollständig.",
        ["Test.Expected"] = "Eine kurze Bestätigung des konfigurierten Modells wird erwartet.",
        ["Costs.Refreshed"] = "Kostendaten aktualisiert.",
        ["Status.Title"] = "Anwendungsstatus",
        ["Status.Thinking"] = "Verarbeitung mit dem konfigurierten Modell...",
        ["Status.Setup"] = "Einrichtung",
        ["Status.Completed"] = "abgeschlossen",
        ["Status.Required"] = "erforderlich",
        ["Status.Pricing"] = "Preis-Cache",
        ["Status.Logs"] = "Protokolle",
        ["Status.Prompts"] = "YAML-Prompts",
        ["Help.Title"] = "Befehlszeile",
        ["Help.Usage"] = "Verwendung: hm [Befehl] [Optionen]",
        ["Help.Version"] = "Zeigt Anwendungs- und Laufzeitversionen.",
        ["Help.Setup"] = "Öffnet die Erst- und KI-Einrichtung.",
        ["Help.Status"] = "Zeigt Konfiguration und lokale Dienste.",
        ["Help.Query"] = "Sendet einen einzelnen Prompt an das konfigurierte Modell.",
        ["Help.Chat"] = "Öffnet einen interaktiven Mehrfachrunden-Chat.",
        ["Help.Test"] = "Führt den YAML-Verbindungsprompt mit Fernschreiber-Effekt aus.",
        ["Help.Costs"] = "Aktualisiert und zeigt Preise, Nutzung und Monatskosten.",
        ["Help.Language"] = "Überschreibt die UI-Sprache: it, en, fr, de, es, vi.",
        ["Help.Font"] = "Installiert JetBrainsMono Nerd Font nach Zustimmung.",
        ["Help.Path"] = "Zeigt, ergänzt, entfernt oder prüft den portablen hm-Pfad.",
        ["Help.ThirdParty"] = "Zeigt direkte Abhängigkeiten und Drittanbieter-Lizenzen.",
        ["Help.Rendering"] = "Deaktiviert Animationen oder Emoji für eingeschränkte Terminals.",
        ["Help.Yes"] = "Autorisiert nur eine explizite PATH- oder Schriftoperation vorab, niemals einen Chat-Befehl.",
        ["Help.DryRun"] = "Simuliert die Schriftinstallation ohne Systemänderung.",
        ["Error.PromptMissing"] = "Prompt-Ressource '{0}' wurde nicht gefunden.",
        ["ThirdParty.Title"] = "Drittanbieter-Software",
        ["ThirdParty.Subtitle"] = "Direkte Laufzeitabhängigkeiten von PromptMeUp.",
        ["ThirdParty.Package"] = "Paket",
        ["ThirdParty.Version"] = "Version",
        ["ThirdParty.License"] = "Lizenz",
        ["ThirdParty.FullNotices"] = "Vollständige Hinweise: THIRD_PARTY_NOTICES.md",
        ["Path.Title"] = "Portabler PATH",
        ["Path.Action"] = "PATH-Aktion auswählen",
        ["Path.Install"] = "Diesen hm-Ordner zum Benutzer-PATH hinzufügen",
        ["Path.Remove"] = "Den verwalteten hm-Ordner aus dem Benutzer-PATH entfernen",
        ["Path.Status"] = "PATH-Status prüfen",
        ["Path.Confirm"] = "Genau diese PATH-Änderung anwenden?",
        ["Path.Present"] = "Dieser hm-Ordner ist bereits im persistenten Benutzer-PATH.",
        ["Path.Missing"] = "Dieser hm-Ordner ist nicht im persistenten Benutzer-PATH.",
        ["Command.Preview"] = "BEFEHLSVORSCHAU // AUTORISIERUNG ERFORDERLICH",
        ["Command.Risk"] = "Risikowert",
        ["Command.AiReview"] = "KI-Prüfung",
        ["Command.LocalReview"] = "Lokale Prüfung",
        ["Command.SendOutput"] = "Bei Ausführung können stdout/stderr lokal gespeichert und in der nächsten Runde an OpenAI gesendet werden.",
        ["Command.Authorize"] = "Diesen exakten Befehl jetzt autorisieren?",
        ["Command.Cancelled"] = "Befehl abgebrochen; nichts wurde ausgeführt.",
        ["Command.Output"] = "Befehlsausgabe",
        ["Command.Running"] = "Autorisierter Befehl wird ausgeführt...",
        ["Common.Back"] = "Zurück"
    };

    /// <summary>Returns translations for newer Vietnamese setup, safety, help, and portable-runtime surfaces.</summary>
    private static IReadOnlyDictionary<string, string> VietnameseCompletion() => new Dictionary<string, string>
    {
        ["Footer.Command"] = "Lệnh",
        ["Footer.Version"] = "Phiên bản",
        ["Footer.Data"] = "Dữ liệu",
        ["Setup.Header"] = "CẤU HÌNH HỆ THỐNG",
        ["Setup.KeyStatus"] = "Trạng thái OPENAI_API_KEY",
        ["Setup.AdminKeyStatus"] = "Trạng thái OPENAI_ADMIN_KEY",
        ["Setup.Cancelled"] = "Đã hủy thiết lập; không lưu thay đổi.",
        ["Setup.CommandReview"] = "Dùng đánh giá AI tùy chọn trước khi cấp quyền chạy lệnh?",
        ["Setup.PromptCaching"] = "Bật bộ nhớ đệm prompt của OpenAI?",
        ["Setup.MemoryLimits"] = "Giới hạn bộ nhớ cho phiên ngắn",
        ["Setup.MaxTurns"] = "Số lượt người dùng tối đa",
        ["Setup.MaxMessage"] = "Số ký tự tối đa mỗi tin nhắn",
        ["Setup.MaxContext"] = "Mức sử dụng cửa sổ ngữ cảnh tối đa (%)",
        ["Setup.MaxCommandOutput"] = "Số ký tự đầu ra lệnh tối đa được lưu",
        ["Setup.CommandTimeout"] = "Thời gian chờ lệnh tính bằng giây",
        ["Setup.Endpoint"] = "Endpoint OpenAI Responses",
        ["Query.Empty"] = "Prompt không được để trống.",
        ["Chat.Assistant"] = "PromptMeUp",
        ["Chat.Hint"] = "Lệnh: /run <lệnh>, /exit, /clear, /costs, /status",
        ["Chat.Pruned"] = "Ngữ cảnh hoạt động đã xóa {0} tin nhắn cũ; nhật ký kiểm toán vẫn đầy đủ.",
        ["Test.Expected"] = "Mô hình đã cấu hình phải trả về một xác nhận ngắn.",
        ["Costs.Refreshed"] = "Đã cập nhật dữ liệu chi phí.",
        ["Status.Title"] = "Trạng thái ứng dụng",
        ["Status.Thinking"] = "Đang xử lý với mô hình đã cấu hình...",
        ["Status.Setup"] = "Thiết lập",
        ["Status.Completed"] = "đã hoàn tất",
        ["Status.Required"] = "bắt buộc",
        ["Status.Pricing"] = "Bộ nhớ đệm giá",
        ["Status.Logs"] = "Nhật ký",
        ["Status.Prompts"] = "Prompt YAML",
        ["Help.Title"] = "Dòng lệnh",
        ["Help.Usage"] = "Cách dùng: hm [lệnh] [tùy chọn]",
        ["Help.Version"] = "Hiển thị phiên bản ứng dụng và runtime.",
        ["Help.Setup"] = "Mở thiết lập ban đầu và AI.",
        ["Help.Status"] = "Hiển thị cấu hình và dịch vụ cục bộ.",
        ["Help.Query"] = "Gửi một prompt đến mô hình đã cấu hình.",
        ["Help.Chat"] = "Mở chat tương tác nhiều lượt.",
        ["Help.Test"] = "Chạy prompt YAML kiểm tra kết nối với hiệu ứng máy đánh chữ.",
        ["Help.Costs"] = "Cập nhật và hiển thị giá, mức sử dụng và chi phí tháng.",
        ["Help.Language"] = "Đổi ngôn ngữ giao diện: it, en, fr, de, es, vi.",
        ["Help.Font"] = "Cài JetBrainsMono Nerd Font khi được cho phép.",
        ["Help.Path"] = "Xem trước, thêm, xóa hoặc kiểm tra thư mục hm trong PATH.",
        ["Help.ThirdParty"] = "Hiển thị phụ thuộc trực tiếp và giấy phép bên thứ ba.",
        ["Help.Rendering"] = "Tắt hoạt ảnh hoặc emoji cho terminal hạn chế.",
        ["Help.Yes"] = "Chỉ cấp quyền trước cho thao tác PATH hoặc font rõ ràng; không bao giờ cho lệnh chat.",
        ["Help.DryRun"] = "Mô phỏng cài font mà không thay đổi hệ thống.",
        ["Error.PromptMissing"] = "Không tìm thấy tài nguyên prompt '{0}'.",
        ["ThirdParty.Title"] = "Phần mềm bên thứ ba",
        ["ThirdParty.Subtitle"] = "Các phụ thuộc runtime trực tiếp được PromptMeUp sử dụng.",
        ["ThirdParty.Package"] = "Gói",
        ["ThirdParty.Version"] = "Phiên bản",
        ["ThirdParty.License"] = "Giấy phép",
        ["ThirdParty.FullNotices"] = "Thông báo đầy đủ: THIRD_PARTY_NOTICES.md",
        ["Path.Title"] = "PATH di động",
        ["Path.Action"] = "Chọn thao tác PATH",
        ["Path.Install"] = "Thêm thư mục hm này vào PATH người dùng",
        ["Path.Remove"] = "Xóa thư mục hm được quản lý khỏi PATH người dùng",
        ["Path.Status"] = "Kiểm tra trạng thái PATH",
        ["Path.Confirm"] = "Áp dụng chính xác thay đổi PATH này?",
        ["Path.Present"] = "Thư mục hm này đã có trong PATH người dùng lâu dài.",
        ["Path.Missing"] = "Thư mục hm này chưa có trong PATH người dùng lâu dài.",
        ["Command.Preview"] = "XEM TRƯỚC LỆNH // CẦN CẤP QUYỀN",
        ["Command.Risk"] = "Điểm rủi ro",
        ["Command.AiReview"] = "Đánh giá AI",
        ["Command.LocalReview"] = "Đánh giá cục bộ",
        ["Command.SendOutput"] = "Nếu chạy, stdout/stderr có thể được lưu cục bộ và gửi tới OpenAI ở lượt tiếp theo.",
        ["Command.Authorize"] = "Cấp quyền chạy chính xác lệnh này ngay bây giờ?",
        ["Command.Cancelled"] = "Đã hủy lệnh; không có gì được thực thi.",
        ["Command.Output"] = "Đầu ra lệnh",
        ["Command.Running"] = "Đang chạy lệnh đã được cấp quyền...",
        ["Common.Back"] = "Quay lại"
    };

    /// <summary>Merges newer translations over an established language baseline.</summary>
    private static IReadOnlyDictionary<string, string> Complete(
        IReadOnlyDictionary<string, string> baseline,
        IReadOnlyDictionary<string, string> additions)
    {
        var completed = baseline.ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.Ordinal);
        foreach (var (key, value) in additions)
        {
            completed[key] = value;
        }

        return completed;
    }
}
