// SPDX-License-Identifier: MIT

namespace PromptMeUp.Services;

internal static partial class UiTextCatalog
{
    /// <summary>Adds all six translations for opt-in skills and reviewed memory learning.</summary>
    private static void AddSkillsAndMemoryEntries(Dictionary<string, LocalizedText> entries)
    {
        entries.Add("Help.Skills", new(
            "Choose and enable tools for files, the web and reminders. Import skills or run their actions, always with your approval.",
            "Scegli e attiva strumenti per file, web e promemoria. Puoi importarli e avviare le loro azioni, sempre con la tua conferma.",
            "Choisissez et activez des outils pour les fichiers, le web et les rappels. Importez des compétences ou lancez leurs actions, toujours avec votre accord.",
            "Wähle und aktiviere Werkzeuge für Dateien, das Web und Erinnerungen. Importiere Skills oder starte ihre Aktionen, immer mit deiner Zustimmung.",
            "Elige y activa herramientas para archivos, web y recordatorios. Importa skills o ejecuta sus acciones, siempre con tu aprobación.",
            "Chọn và bật công cụ cho tệp, web và lời nhắc. Nhập kỹ năng hoặc chạy thao tác của chúng, luôn cần bạn xác nhận."));
        entries.Add("Help.Learning", new(
            "Choose whether to keep messages from future chats for memory suggestions. You can also read or delete the collected messages here.",
            "Scegli se conservare i messaggi delle prossime chat per suggerire ricordi. Qui puoi anche leggere o cancellare quelli raccolti.",
            "Choisissez de conserver ou non les messages des prochains chats pour suggérer des souvenirs. Ici, vous pouvez aussi lire ou supprimer les messages collectés.",
            "Entscheide, ob Nachrichten aus künftigen Chats für Erinnerungsvorschläge gespeichert werden. Hier kannst du gesammelte Nachrichten auch lesen oder löschen.",
            "Elige si guardar mensajes de próximos chats para sugerir recuerdos. Aquí también puedes leer o borrar los mensajes recopilados.",
            "Chọn có giữ tin nhắn từ các cuộc trò chuyện sau để đề xuất ghi nhớ hay không. Bạn cũng có thể đọc hoặc xóa tin nhắn đã thu thập tại đây."));
        entries.Add("Help.Proposals", new(
            "Review suggested memories and changes: edit the text, approve what you want to keep, or reject the rest.",
            "Rivedi i ricordi suggeriti e le modifiche proposte: correggi il testo, approva ciò che vuoi tenere o scarta il resto.",
            "Examinez les souvenirs et changements proposés : corrigez le texte, approuvez ce que vous souhaitez garder ou rejetez le reste.",
            "Prüfe vorgeschlagene Erinnerungen und Änderungen: Bearbeite den Text, genehmige das Gewünschte oder verwerfe den Rest.",
            "Revisa los recuerdos y cambios propuestos: corrige el texto, aprueba lo que quieras conservar o descarta el resto.",
            "Xem lại ghi nhớ và thay đổi được đề xuất: sửa nội dung, duyệt phần muốn giữ hoặc bỏ phần còn lại."));
        entries.Add("Help.Dream", new(
            "Ask AI to suggest memories from collected messages, such as how you prefer answers. Then choose which memories to save.",
            "Chiedi all’AI di ricavare ricordi dai messaggi raccolti, per esempio come preferisci le risposte. Poi scegli quali salvare.",
            "Demandez à l’IA de proposer des souvenirs à partir des messages collectés, comme votre style de réponse préféré. Choisissez ensuite lesquels enregistrer.",
            "Lass die KI aus gesammelten Nachrichten Erinnerungen vorschlagen, etwa deinen bevorzugten Antwortstil. Wähle danach, was gespeichert wird.",
            "Pide a la IA que sugiera recuerdos a partir de mensajes recopilados, como tu estilo de respuesta preferido. Luego elige cuáles guardar.",
            "Nhờ AI đề xuất ghi nhớ từ tin nhắn đã thu thập, chẳng hạn cách bạn muốn nhận câu trả lời. Sau đó chọn ghi nhớ cần lưu."));
        entries.Add("Help.Heartbeat", new(
            "Find duplicate memories and suggested merges. You can also request an AI review; every change needs your approval.",
            "Trova ricordi duplicati e propone di unirli. Puoi chiedere anche una revisione AI; ogni modifica richiede la tua conferma.",
            "Repérez les souvenirs en double et les regroupements proposés. Vous pouvez aussi demander un examen IA ; chaque changement nécessite votre accord.",
            "Finde doppelte Erinnerungen und Vorschläge zum Zusammenführen. Du kannst auch eine KI-Prüfung anfordern; jede Änderung braucht deine Zustimmung.",
            "Encuentra recuerdos duplicados y propuestas para unirlos. También puedes pedir una revisión con IA; cada cambio requiere tu aprobación.",
            "Tìm ghi nhớ trùng lặp và đề xuất gộp chúng. Bạn cũng có thể nhờ AI kiểm tra; mọi thay đổi đều cần bạn duyệt."));
        entries.Add("Lab.SkillName.filesystem", new("Files and folders", "File e cartelle", "Fichiers et dossiers", "Dateien und Ordner", "Archivos y carpetas", "Tệp và thư mục"));
        entries.Add("Lab.SkillName.git", new("Git history and changes", "Cronologia e modifiche Git", "Historique et modifications Git", "Git-Verlauf und Änderungen", "Historial y cambios de Git", "Lịch sử và thay đổi Git"));
        entries.Add("Lab.SkillName.clipboard", new("Clipboard", "Appunti", "Presse-papiers", "Zwischenablage", "Portapapeles", "Bộ nhớ tạm"));
        entries.Add("Lab.SkillName.concat-files", new("Combine text files", "Unisci file di testo", "Regrouper des fichiers texte", "Textdateien zusammenführen", "Combinar archivos de texto", "Ghép tệp văn bản"));
        entries.Add("Lab.SkillName.http_request", new("Requests to websites", "Richieste ai siti web", "Requêtes vers des sites web", "Anfragen an Websites", "Solicitudes a sitios web", "Yêu cầu tới trang web"));
        entries.Add("Lab.SkillName.screenshot", new("Screen capture", "Cattura schermo", "Capture d’écran", "Bildschirmfoto", "Captura de pantalla", "Chụp màn hình"));
        entries.Add("Lab.SkillName.set_reminder", new("Reminders", "Promemoria", "Rappels", "Erinnerungen", "Recordatorios", "Lời nhắc"));
        entries.Add("Lab.SkillName.system_info", new("Computer information", "Informazioni sul computer", "Informations sur l’ordinateur", "Computerinformationen", "Información del equipo", "Thông tin máy tính"));
        entries.Add("Lab.SkillName.timezone_convert", new("Time zones", "Fusi orari", "Fuseaux horaires", "Zeitzonen", "Zonas horarias", "Múi giờ"));
        entries.Add("Lab.SkillName.web_search", new("Web search", "Ricerca sul web", "Recherche web", "Websuche", "Búsqueda web", "Tìm kiếm trên web"));
        entries.Add("Lab.ScreenshotPrivacy", new("Close sensitive windows before capture. Images cannot be redacted and are saved locally, not uploaded.", "Chiudi le finestre sensibili prima della cattura. Le immagini non possono essere oscurate e vengono salvate localmente, senza caricamento.", "Fermez les fenêtres sensibles avant la capture. Les images ne peuvent pas être expurgées ; elles sont enregistrées localement, sans envoi.", "Schließe vor der Aufnahme vertrauliche Fenster. Bilder können nicht bereinigt werden und werden lokal gespeichert, nicht hochgeladen.", "Cierra las ventanas sensibles antes de capturar. Las imágenes no pueden depurarse; se guardan localmente, sin subirse.", "Đóng cửa sổ nhạy cảm trước khi chụp. Ảnh không thể che bí mật tự động và chỉ lưu cục bộ, không tải lên."));
        entries.Add("Lab.Title", new("Skills and memory", "Skills e memoria", "Compétences et mémoire", "Skills und Gedächtnis", "Skills y memoria", "Kỹ năng và bộ nhớ"));
        entries.Add("Lab.Invalid", new("The data is invalid, has changed, or is too large. Nothing was approved.", "I dati non sono validi, sono cambiati o sono troppo grandi. Nessuna modifica è stata approvata.", "Les données sont invalides, ont changé ou sont trop volumineuses. Rien n’a été approuvé.", "Die Daten sind ungültig, wurden geändert oder sind zu groß. Nichts wurde genehmigt.", "Los datos no son válidos, han cambiado o son demasiado grandes. No se aprobó nada.", "Dữ liệu không hợp lệ, đã thay đổi hoặc quá lớn. Chưa phê duyệt gì."));
        entries.Add("Lab.Platform", new("Unavailable on this operating system", "Non disponibile su questo sistema operativo", "Indisponible sur ce système", "Auf diesem Betriebssystem nicht verfügbar", "No disponible en este sistema", "Không khả dụng trên hệ điều hành này"));
        entries.Add("Lab.Dependency", new("Missing requirement: {0}", "Requisito mancante: {0}", "Prérequis manquant : {0}", "Fehlende Voraussetzung: {0}", "Requisito ausente: {0}", "Thiếu yêu cầu: {0}"));
        entries.Add("Lab.SkillTooLarge", new("Skill {0} exceeds the {1}-token instruction budget. Shorten its instructions before enabling or selecting it.", "La skill {0} supera il budget di {1} token per le istruzioni. Accorciale prima di abilitarla o selezionarla.", "La compétence {0} dépasse le budget de {1} jetons. Raccourcissez ses instructions avant de l’activer ou de la sélectionner.", "Skill {0} überschreitet das Anweisungslimit von {1} Tokens. Kürze die Anweisungen vor dem Aktivieren oder Auswählen.", "La skill {0} supera el presupuesto de {1} tokens. Acorta sus instrucciones antes de habilitarla o seleccionarla.", "Kỹ năng {0} vượt ngân sách hướng dẫn {1} token. Hãy rút ngắn hướng dẫn trước khi bật hoặc chọn."));
        entries.Add("Lab.Enable", new("Turn on skills and memory", "Attiva skills e memoria", "Activer les compétences et la mémoire", "Skills und Gedächtnis aktivieren", "Activar skills y memoria", "Bật kỹ năng và bộ nhớ"));
        entries.Add("Lab.Disable", new("Turn off skills and memory; delete collected messages and suggestions", "Disattiva skills e memoria; cancella messaggi raccolti e suggerimenti", "Désactiver compétences et mémoire ; supprimer messages collectés et suggestions", "Skills und Gedächtnis deaktivieren; erfasste Nachrichten und Vorschläge löschen", "Desactivar skills y memoria; borrar mensajes recopilados y sugerencias", "Tắt kỹ năng và bộ nhớ; xóa tin nhắn đã thu thập và đề xuất"));
        entries.Add("Lab.Skills", new("Skills", "Skills", "Compétences", "Skills", "Skills", "Kỹ năng"));
        entries.Add("Lab.GeneralGroup", new("General", "Generale", "Général", "Allgemein", "General", "Chung"));
        entries.Add("Lab.GeneralEnabledDescription", new("Configure skill selection and availability.", "Configura la selezione e la disponibilità delle skill.", "Configurez la sélection et la disponibilité des compétences.", "Konfiguriere Skill-Auswahl und Verfügbarkeit.", "Configura la selección y disponibilidad de skills.", "Cấu hình việc chọn và sử dụng kỹ năng."));
        entries.Add("Lab.GeneralDisabledDescription", new("Turn on skills and memory before configuring them.", "Attiva skills e memoria prima di configurarle.", "Activez les compétences et la mémoire avant de les configurer.", "Aktiviere Skills und Gedächtnis, bevor du sie konfigurierst.", "Activa skills y memoria antes de configurarlas.", "Bật kỹ năng và bộ nhớ trước khi cấu hình."));
        entries.Add("Lab.InstalledGroup", new("Installed skills", "Skill installate", "Compétences installées", "Installierte Skills", "Skills instaladas", "Kỹ năng đã cài đặt"));
        entries.Add("Lab.InstalledDescription", new("Review installed packages and use their commands directly here.", "Controlla i pacchetti installati e usa i loro comandi direttamente qui.", "Examinez les paquets installés et utilisez leurs commandes directement ici.", "Prüfe installierte Pakete und verwende ihre Befehle direkt hier.", "Revisa los paquetes instalados y usa sus comandos directamente aquí.", "Xem các gói đã cài đặt và dùng lệnh của chúng ngay tại đây."));
        entries.Add("Lab.ImportGroup", new("Import", "Importa", "Importer", "Importieren", "Importar", "Nhập"));
        entries.Add("Lab.ImportDescription", new("Inspect and import a local skill package from a ZIP file.", "Controlla e importa un pacchetto skill locale da un file ZIP.", "Inspectez et importez un paquet de compétence local depuis un fichier ZIP.", "Prüfe und importiere ein lokales Skill-Paket aus einer ZIP-Datei.", "Inspecciona e importa un paquete de skill local desde un archivo ZIP.", "Kiểm tra và nhập gói kỹ năng cục bộ từ tệp ZIP."));
        entries.Add("Lab.Commands", new("Commands", "Comandi", "Commandes", "Befehle", "Comandos", "Lệnh"));
        entries.Add("Lab.CommandPosition", new("Command {0} of {1}", "Comando {0} di {1}", "Commande {0} sur {1}", "Befehl {0} von {1}", "Comando {0} de {1}", "Lệnh {0} trên {1}"));
        entries.Add("Lab.DetailPosition", new("Detail line {0} of {1}", "Riga dettaglio {0} di {1}", "Ligne de détail {0} sur {1}", "Detailzeile {0} von {1}", "Línea de detalle {0} de {1}", "Dòng chi tiết {0} trên {1}"));
        entries.Add("Lab.RunSkillAction", new("Run {0}. {1}", "Esegui {0}. {1}", "Exécuter {0}. {1}", "{0} ausführen. {1}", "Ejecutar {0}. {1}", "Chạy {0}. {1}"));
        entries.Add("Lab.MenuNotice", new("Choose a section on the left, then use its commands here. Each change keeps its safety checks.", "Scegli una sezione a sinistra, poi usa qui i suoi comandi. Ogni modifica mantiene i controlli di sicurezza.", "Choisissez une section à gauche, puis utilisez ses commandes ici. Chaque modification conserve ses contrôles de sécurité.", "Wähle links einen Bereich und nutze seine Befehle hier. Jede Änderung behält ihre Sicherheitsprüfungen.", "Elige una sección a la izquierda y usa aquí sus comandos. Cada cambio mantiene sus controles de seguridad.", "Chọn một mục bên trái rồi dùng lệnh tại đây. Mỗi thay đổi vẫn giữ các kiểm tra an toàn."));
        entries.Add("Lab.MenuFooter", new("1–{0}: sections | Up/Down: move | Enter/Right: commands/run | Tab: panel | F6: area | Esc/Q: back", "1–{0}: sezioni | Su/Giù: sposta | Invio/Destra: comandi/esegui | Tab: pannello | F6: area | Esc/Q: indietro", "1–{0} : sections | Haut/Bas : déplacer | Entrée/Droite : commandes/exécuter | Tab : panneau | F6 : zone | Échap/Q : retour", "1–{0}: Bereiche | Auf/Ab: bewegen | Enter/Rechts: Befehle/ausführen | Tab: Bereich | F6: Fokus | Esc/Q: zurück", "1–{0}: secciones | Arriba/Abajo: mover | Intro/Derecha: comandos/ejecutar | Tab: panel | F6: área | Esc/Q: volver", "1–{0}: mục | Lên/Xuống: di chuyển | Enter/Phải: lệnh/chạy | Tab: bảng | F6: vùng | Esc/Q: quay lại"));
        entries.Add("Lab.MenuFooterCompact", new("Up/Down: move | Enter: open/run | F6: area | Esc/Q: back", "Su/Giù: sposta | Invio: apri/esegui | F6: area | Esc/Q: indietro", "Haut/Bas : déplacer | Entrée : ouvrir/exécuter | F6 : zone | Échap/Q : retour", "Auf/Ab: bewegen | Enter: öffnen/ausführen | F6: Fokus | Esc/Q: zurück", "Arriba/Abajo: mover | Intro: abrir/ejecutar | F6: área | Esc/Q: volver", "Lên/Xuống: di chuyển | Enter: mở/chạy | F6: vùng | Esc/Q: quay lại"));
        entries.Add("Lab.MenuEditorFooter", new("Type to edit | Enter/Ctrl+Enter: apply | Arrows/Home/End: caret | Ctrl+U: clear | Esc: commands", "Scrivi per modificare | Invio/Ctrl+Invio: applica | Frecce/Home/End: cursore | Ctrl+U: svuota | Esc: comandi", "Saisir pour modifier | Entrée/Ctrl+Entrée : appliquer | Flèches/Début/Fin : curseur | Ctrl+U : effacer | Échap : commandes", "Tippen zum Bearbeiten | Enter/Strg+Enter: anwenden | Pfeile/Pos1/Ende: Cursor | Strg+U: leeren | Esc: Befehle", "Escribe para editar | Intro/Ctrl+Intro: aplicar | Flechas/Inicio/Fin: cursor | Ctrl+U: borrar | Esc: comandos", "Gõ để sửa | Enter/Ctrl+Enter: áp dụng | Phím mũi tên/Home/End: con trỏ | Ctrl+U: xóa | Esc: lệnh"));
        entries.Add("Lab.MenuEditorFooterCompact", new("Enter/Ctrl+Enter: apply | Ctrl+U: clear | Esc: commands", "Invio/Ctrl+Invio: applica | Ctrl+U: svuota | Esc: comandi", "Entrée/Ctrl+Entrée : appliquer | Ctrl+U : effacer | Échap : commandes", "Enter/Strg+Enter: anwenden | Strg+U: leeren | Esc: Befehle", "Intro/Ctrl+Intro: aplicar | Ctrl+U: borrar | Esc: comandos", "Enter/Ctrl+Enter: áp dụng | Ctrl+U: xóa | Esc: lệnh"));
        entries.Add("Lab.Learning", new("Memory", "Memoria", "Mémoire", "Gedächtnis", "Memoria", "Bộ nhớ"));
        entries.Add("Lab.Proposals", new("Suggested memories", "Ricordi suggeriti", "Souvenirs suggérés", "Vorgeschlagene Erinnerungen", "Recuerdos sugeridos", "Ghi nhớ được đề xuất"));
        entries.Add("Lab.Dream", new("Suggest memories from collected messages (Dream)", "Suggerisci ricordi dai messaggi raccolti (Dream)", "Suggérer des souvenirs à partir des messages collectés (Dream)", "Erinnerungen aus erfassten Nachrichten vorschlagen (Dream)", "Sugerir recuerdos a partir de mensajes recopilados (Dream)", "Đề xuất ghi nhớ từ tin nhắn đã thu thập (Dream)"));
        entries.Add("Lab.Heartbeat", new("Review saved memories (Heartbeat)", "Controlla i ricordi salvati (Heartbeat)", "Examiner les souvenirs enregistrés (Heartbeat)", "Gespeicherte Erinnerungen prüfen (Heartbeat)", "Revisar recuerdos guardados (Heartbeat)", "Kiểm tra ghi nhớ đã lưu (Heartbeat)"));
        entries.Add("Lab.Back", new("Back", "Indietro", "Retour", "Zurück", "Volver", "Quay lại"));
        entries.Add("Lab.Confirm", new("Confirm", "Conferma", "Confirmer", "Bestätigen", "Confirmar", "Xác nhận"));
        entries.Add("Lab.Cancel", new("Cancel", "Annulla", "Annuler", "Abbrechen", "Cancelar", "Hủy"));
        entries.Add("Lab.Disabled", new("First turn on skills and memory with hm --skills.", "Prima attiva skills e memoria con hm --skills.", "Activez d’abord les compétences et la mémoire avec hm --skills.", "Zuerst Skills und Gedächtnis mit hm --skills aktivieren.", "Primero activa skills y memoria con hm --skills.", "Trước tiên bật kỹ năng và bộ nhớ bằng hm --skills."));
        entries.Add("Lab.Activate", new("Turn on this skill", "Attiva questa skill", "Activer cette compétence", "Diesen Skill aktivieren", "Activar esta skill", "Bật kỹ năng này"));
        entries.Add("Lab.Deactivate", new("Turn off this skill", "Disattiva questa skill", "Désactiver cette compétence", "Diesen Skill deaktivieren", "Desactivar esta skill", "Tắt kỹ năng này"));
        entries.Add("Lab.Select", new("Use this skill for upcoming questions", "Usa questa skill nelle prossime domande", "Utiliser cette compétence pour les prochaines questions", "Diesen Skill für die nächsten Fragen verwenden", "Usar esta skill en las próximas preguntas", "Dùng kỹ năng này cho các câu hỏi tiếp theo"));
        entries.Add("Lab.ClearSelection", new("Remove the fixed skill for questions", "Rimuovi la skill fissa per le domande", "Retirer la compétence fixe pour les questions", "Feste Skill-Auswahl für Fragen aufheben", "Quitar la skill fija para las preguntas", "Bỏ kỹ năng được dùng cố định cho câu hỏi"));
        entries.Add("Lab.Automatic", new("Choose skills based on the question", "Scegli le skill in base alla domanda", "Choisir les compétences selon la question", "Skills passend zur Frage auswählen", "Elegir skills según la pregunta", "Chọn kỹ năng phù hợp với câu hỏi"));
        entries.Add("Lab.Import", new("Import a skill from ZIP", "Importa una skill da ZIP", "Importer une compétence depuis un ZIP", "Skill aus einer ZIP-Datei importieren", "Importar una skill desde un ZIP", "Nhập kỹ năng từ tệp ZIP"));
        entries.Add("Lab.Path", new("File or directory path", "Percorso del file o cartella", "Chemin du fichier ou dossier", "Datei- oder Verzeichnispfad", "Ruta del archivo o carpeta", "Đường dẫn tệp hoặc thư mục"));
        entries.Add("Lab.Run", new("Choose an action to run", "Scegli un’azione da eseguire", "Choisir une action à exécuter", "Aktion zum Ausführen auswählen", "Elegir una acción para ejecutar", "Chọn thao tác cần thực hiện"));
        entries.Add("Lab.Enabled", new("Enabled", "Abilitato", "Activé", "Aktiviert", "Habilitado", "Đã bật"));
        entries.Add("Lab.Off", new("Disabled", "Disabilitato", "Désactivé", "Deaktiviert", "Deshabilitado", "Đã tắt"));
        entries.Add("Lab.Active", new("Active skills: {0}", "Skills attive: {0}", "Compétences actives : {0}", "Aktive Skills: {0}", "Skills activas: {0}", "Kỹ năng đang dùng: {0}"));
        entries.Add("Lab.Source", new("Source", "Provenienza", "Source", "Quelle", "Origen", "Nguồn"));
        entries.Add("Lab.Package", new("How this skill works", "Come funziona questa skill", "Fonctionnement de cette compétence", "So funktioniert dieser Skill", "Cómo funciona esta skill", "Cách kỹ năng này hoạt động"));
        entries.Add("Lab.Capture", new("Collect my future messages for memory suggestions (30 days, global)", "Raccogli i miei prossimi messaggi per suggerire ricordi (30 giorni, globale)", "Collecter mes prochains messages pour suggérer des souvenirs (30 jours, global)", "Meine künftigen Nachrichten für Erinnerungsvorschläge erfassen (30 Tage, global)", "Recopilar mis próximos mensajes para sugerir recuerdos (30 días, global)", "Thu thập tin nhắn tiếp theo của tôi để đề xuất ghi nhớ (30 ngày, toàn cục)"));
        entries.Add("Lab.EvidenceSummary", new("{0} items ready for review; {1} omitted for size.", "{0} elementi pronti da esaminare; {1} omessi per dimensione.", "{0} éléments prêts à examiner ; {1} omis par taille.", "{0} Elemente bereit zur Prüfung; {1} wegen Größe ausgelassen.", "{0} elementos listos para revisar; {1} omitidos por tamaño.", "{0} mục sẵn sàng xem xét; {1} mục bị bỏ qua do kích thước."));
        entries.Add("Lab.CaptureNotice", new("Collection saves copies of your messages on this device with recognizable credentials hidden. Dream sends the displayed messages to OpenAI only after your confirmation. Turning collection off deletes collected messages and suggestions; saved memories remain.", "La raccolta salva sul dispositivo copie dei tuoi messaggi con le credenziali riconoscibili oscurate. Dream invia i messaggi mostrati a OpenAI solo dopo la tua conferma. Disattivare la raccolta elimina messaggi raccolti e suggerimenti; i ricordi salvati restano.", "La collecte conserve sur cet appareil des copies de vos messages en masquant les identifiants secrets reconnaissables. Dream envoie les messages affichés à OpenAI uniquement après votre confirmation. Désactiver la collecte supprime messages collectés et suggestions ; les souvenirs enregistrés restent.", "Die Erfassung speichert Kopien deiner Nachrichten auf diesem Gerät und verdeckt erkennbare Zugangsdaten. Dream sendet die angezeigten Nachrichten erst nach deiner Bestätigung an OpenAI. Ausschalten löscht erfasste Nachrichten und Vorschläge; gespeicherte Erinnerungen bleiben.", "La recopilación guarda copias de tus mensajes en este dispositivo ocultando credenciales reconocibles. Dream envía los mensajes mostrados a OpenAI solo tras tu confirmación. Desactivarla elimina mensajes recopilados y sugerencias; los recuerdos guardados permanecen.", "Tính năng thu thập lưu bản sao tin nhắn trên thiết bị này và che thông tin xác thực có thể nhận diện. Dream chỉ gửi các tin nhắn hiển thị tới OpenAI sau khi bạn xác nhận. Tắt thu thập sẽ xóa tin nhắn đã thu thập và đề xuất; ghi nhớ đã lưu vẫn còn."));
        entries.Add("Lab.Reminder", new("Remind me at chat start to review saved memories", "Ricordami all’inizio della chat di controllare i ricordi salvati", "Me rappeler au début du chat de vérifier les souvenirs enregistrés", "Beim Chatstart an die Prüfung gespeicherter Erinnerungen erinnern", "Recordarme al iniciar el chat que revise los recuerdos guardados", "Nhắc tôi kiểm tra ghi nhớ đã lưu khi bắt đầu trò chuyện"));
        entries.Add("Lab.Due", new("It is time to review your saved memories. Run hm --heartbeat when convenient.", "È il momento di controllare i ricordi salvati. Avvia hm --heartbeat quando vuoi.", "Il est temps de vérifier vos souvenirs enregistrés. Lancez hm --heartbeat quand vous le souhaitez.", "Es ist Zeit, deine gespeicherten Erinnerungen zu prüfen. Starte bei Gelegenheit hm --heartbeat.", "Es momento de revisar tus recuerdos guardados. Ejecuta hm --heartbeat cuando quieras.", "Đã đến lúc kiểm tra ghi nhớ đã lưu. Chạy hm --heartbeat khi thuận tiện."));
        entries.Add("Lab.Clear", new("Delete collected messages and memory suggestions", "Cancella messaggi raccolti e ricordi suggeriti", "Supprimer les messages collectés et les souvenirs suggérés", "Erfasste Nachrichten und Erinnerungsvorschläge löschen", "Borrar mensajes recopilados y recuerdos sugeridos", "Xóa tin nhắn đã thu thập và ghi nhớ được đề xuất"));
        entries.Add("Lab.Observations", new("Collected messages", "Messaggi raccolti", "Messages collectés", "Erfasste Nachrichten", "Mensajes recopilados", "Tin nhắn đã thu thập"));
        entries.Add("Lab.None", new("Nothing to review.", "Niente da valutare.", "Rien à examiner.", "Nichts zu prüfen.", "Nada que revisar.", "Không có gì cần xem xét."));
        entries.Add("Lab.Approve", new("Approve the displayed change", "Approva la modifica mostrata", "Approuver la modification affichée", "Angezeigte Änderung genehmigen", "Aprobar el cambio mostrado", "Phê duyệt thay đổi hiển thị"));
        entries.Add("Lab.Reject", new("Reject proposal", "Scarta proposta", "Rejeter la proposition", "Vorschlag ablehnen", "Rechazar propuesta", "Từ chối đề xuất"));
        entries.Add("Lab.Edit", new("Edit proposed text", "Modifica testo proposto", "Modifier le texte proposé", "Vorgeschlagenen Text bearbeiten", "Editar texto propuesto", "Sửa nội dung đề xuất"));
        entries.Add("Lab.Before", new("Before", "Prima", "Avant", "Vorher", "Antes", "Trước"));
        entries.Add("Lab.After", new("After", "Dopo", "Après", "Nachher", "Después", "Sau"));
        entries.Add("Lab.Reason", new("Reason", "Motivazione", "Motif", "Begründung", "Motivo", "Lý do"));
        entries.Add("Lab.Sources", new("Content to review", "Contenuti da esaminare", "Contenu à examiner", "Zu prüfende Inhalte", "Contenido para revisar", "Nội dung cần xem xét"));
        entries.Add("Lab.Saved", new("Saved.", "Salvato.", "Enregistré.", "Gespeichert.", "Guardado.", "Đã lưu."));
        entries.Add("Lab.ReviewCount", new("Created {0} memory suggestions. Review them with hm --proposals.", "Creati {0} suggerimenti per i ricordi. Rivedili con hm --proposals.", "{0} suggestions pour vos souvenirs créées. Examinez-les avec hm --proposals.", "{0} Erinnerungsvorschläge erstellt. Mit hm --proposals prüfen.", "Se crearon {0} sugerencias para tus recuerdos. Revísalas con hm --proposals.", "Đã tạo {0} đề xuất về ghi nhớ. Xem lại bằng hm --proposals."));
        entries.Add("Lab.Share", new("Send the displayed evidence to OpenAI for analysis? This uses API tokens.", "Inviare le evidenze mostrate a OpenAI per l’analisi? Consuma token API.", "Envoyer les preuves affichées à OpenAI ? Cela consomme des jetons API.", "Angezeigte Belege zur Analyse an OpenAI senden? Dies verbraucht API-Tokens.", "¿Enviar las evidencias mostradas a OpenAI? Consume tokens API.", "Gửi bằng chứng hiển thị đến OpenAI để phân tích? Thao tác dùng token API."));
        entries.Add("Lab.NeedSessions", new("Dream needs collected messages from at least two different sessions.", "Dream richiede messaggi raccolti da almeno due sessioni diverse.", "Dream a besoin de messages collectés dans au moins deux sessions différentes.", "Dream benötigt erfasste Nachrichten aus mindestens zwei verschiedenen Sitzungen.", "Dream necesita mensajes recopilados de al menos dos sesiones distintas.", "Dream cần tin nhắn được thu thập từ ít nhất hai phiên khác nhau."));
        entries.Add("Lab.ManualOnly", new("If you change any of this skill’s files, you must turn the skill on again.", "Se modifichi i file di questa skill, dovrai attivarla di nuovo.", "Si vous modifiez un fichier de cette compétence, vous devez la réactiver.", "Wenn du Dateien dieses Skills änderst, musst du ihn erneut aktivieren.", "Si modificas algún archivo de esta skill, deberás activarla de nuevo.", "Nếu thay đổi bất kỳ tệp nào của kỹ năng này, bạn phải bật lại kỹ năng."));
        entries.Add("Lab.Arguments", new("PowerShell parameters as a JSON object (no secrets)", "Parametri PowerShell come oggetto JSON (senza segreti)", "Paramètres PowerShell en objet JSON (sans secrets)", "PowerShell-Parameter als JSON-Objekt (ohne Geheimnisse)", "Parámetros PowerShell como objeto JSON (sin secretos)", "Tham số PowerShell dạng đối tượng JSON (không chứa bí mật)"));
        entries.Add("Lab.LastRun", new("Last completed review", "Ultimo controllo completato", "Dernier examen terminé", "Letzte abgeschlossene Prüfung", "Última revisión completada", "Lần kiểm tra hoàn tất gần nhất"));
        entries.Add("Lab.ReviewButton", new("Suggested memories", "Ricordi suggeriti", "Souvenirs suggérés", "Vorgeschlagene Erinnerungen", "Recuerdos sugeridos", "Ghi nhớ được đề xuất"));
        entries.Add("Lab.SkillActionInvalid", new("The skill could not complete. Check its parameters, permissions, and supported platform.", "La skill non è riuscita a completare l’azione. Controlla parametri, permessi e piattaforma supportata.", "La compétence n’a pas pu terminer. Vérifiez les paramètres, les autorisations et la plateforme prise en charge.", "Der Skill konnte nicht abgeschlossen werden. Prüfe Parameter, Berechtigungen und unterstützte Plattform.", "La skill no pudo completar la acción. Revisa parámetros, permisos y plataforma compatible.", "Kỹ năng không thể hoàn tất. Kiểm tra tham số, quyền và nền tảng được hỗ trợ."));
        entries.Add("Lab.ForgetNotice", new("Deleting this memory also permanently clears all collected messages and suggestions. Other saved memories and earlier history remain.", "Eliminare questo ricordo cancella definitivamente anche tutti i messaggi raccolti e i suggerimenti. Gli altri ricordi salvati e la cronologia precedente restano.", "Supprimer ce souvenir efface aussi définitivement tous les messages conservés et les suggestions. Les autres souvenirs et l’historique restent.", "Diese Erinnerung zu löschen entfernt auch alle gesammelten Nachrichten und Vorschläge endgültig. Andere Erinnerungen und der bisherige Verlauf bleiben.", "Eliminar este recuerdo también borra definitivamente todos los mensajes conservados y las sugerencias. Los demás recuerdos y el historial permanecen.", "Xóa ghi nhớ này cũng xóa vĩnh viễn mọi tin nhắn đã thu thập và đề xuất. Ghi nhớ khác và lịch sử trước đó vẫn còn."));
        entries.Add("Lab.ConcatInvalid", new("The selected paths or files are invalid, linked, or exceed the concatenation limits.", "I percorsi o i file selezionati non sono validi, sono collegamenti o superano i limiti di concatenazione.", "Les chemins ou fichiers sélectionnés sont invalides, sont des liens ou dépassent les limites de concaténation.", "Die gewählten Pfade oder Dateien sind ungültig, sind Verknüpfungen oder überschreiten die Zusammenführungslimits.", "Las rutas o los archivos seleccionados no son válidos, son enlaces o superan los límites de concatenación.", "Đường dẫn hoặc tệp đã chọn không hợp lệ, là liên kết hoặc vượt giới hạn ghép tệp."));
    }
}
