// SPDX-License-Identifier: MIT

namespace PromptMeUp.Services;

internal static partial class UiTextCatalog
{
    /// <summary>Adds all six translations for opt-in skills and reviewed memory learning.</summary>
    private static void AddExperimentalEntries(Dictionary<string, LocalizedText> entries)
    {
        entries.Add("Lab.ScreenshotPrivacy", new("Close sensitive windows before capture. Images cannot be redacted and are saved locally, not uploaded.", "Chiudi le finestre sensibili prima della cattura. Le immagini non possono essere oscurate e vengono salvate localmente, senza caricamento.", "Fermez les fenêtres sensibles avant la capture. Les images ne peuvent pas être expurgées ; elles sont enregistrées localement, sans envoi.", "Schließe vor der Aufnahme vertrauliche Fenster. Bilder können nicht bereinigt werden und werden lokal gespeichert, nicht hochgeladen.", "Cierra las ventanas sensibles antes de capturar. Las imágenes no pueden depurarse; se guardan localmente, sin subirse.", "Đóng cửa sổ nhạy cảm trước khi chụp. Ảnh không thể che bí mật tự động và chỉ lưu cục bộ, không tải lên."));
        entries.Add("Lab.Title", new("Experimental skills and memory", "Skills e memoria sperimentali", "Compétences et mémoire expérimentales", "Experimentelle Skills und Erinnerungen", "Skills y memoria experimentales", "Kỹ năng và ghi nhớ thử nghiệm"));
        entries.Add("Lab.Invalid", new("Invalid, changed, or oversized experimental data. Nothing was approved.", "Dati sperimentali non validi, modificati o troppo grandi. Nessuna approvazione.", "Données expérimentales invalides, modifiées ou trop volumineuses. Rien n’a été approuvé.", "Experimentelle Daten ungültig, geändert oder zu groß. Nichts wurde genehmigt.", "Datos experimentales inválidos, modificados o demasiado grandes. No se aprobó nada.", "Dữ liệu thử nghiệm không hợp lệ, đã đổi hoặc quá lớn. Chưa phê duyệt gì."));
        entries.Add("Lab.Platform", new("Unavailable on this operating system", "Non disponibile su questo sistema operativo", "Indisponible sur ce système", "Auf diesem Betriebssystem nicht verfügbar", "No disponible en este sistema", "Không khả dụng trên hệ điều hành này"));
        entries.Add("Lab.Dependency", new("Missing requirement: {0}", "Requisito mancante: {0}", "Prérequis manquant : {0}", "Fehlende Voraussetzung: {0}", "Requisito ausente: {0}", "Thiếu yêu cầu: {0}"));
        entries.Add("Lab.Enable", new("Enable experiment for this project", "Abilita esperimento per questo progetto", "Activer pour ce projet", "Experiment für dieses Projekt aktivieren", "Activar experimento para este proyecto", "Bật thử nghiệm cho dự án này"));
        entries.Add("Lab.Disable", new("Disable experiment and clear learning evidence", "Disabilita esperimento e cancella le osservazioni", "Désactiver et effacer les observations", "Experiment deaktivieren und Beobachtungen löschen", "Desactivar y borrar observaciones", "Tắt thử nghiệm và xóa quan sát"));
        entries.Add("Lab.Skills", new("Skills", "Skills", "Compétences", "Skills", "Skills", "Kỹ năng"));
        entries.Add("Lab.Learning", new("Learning preferences", "Preferenze di apprendimento", "Préférences d’apprentissage", "Lerneinstellungen", "Preferencias de aprendizaje", "Tùy chọn học"));
        entries.Add("Lab.Proposals", new("To review", "Da valutare", "À examiner", "Zu prüfen", "Por revisar", "Cần xem xét"));
        entries.Add("Lab.Dream", new("Dream: reflect across sessions", "Dream: riflessione tra sessioni", "Dream : réflexion entre sessions", "Dream: Sitzungen übergreifend reflektieren", "Dream: reflexión entre sesiones", "Dream: suy ngẫm qua các phiên"));
        entries.Add("Lab.Heartbeat", new("Heartbeat: review saved memories", "Heartbeat: revisione delle memorie", "Heartbeat : examiner les mémoires", "Heartbeat: Erinnerungen prüfen", "Heartbeat: revisar memorias", "Heartbeat: kiểm tra ghi nhớ"));
        entries.Add("Lab.Back", new("Back", "Indietro", "Retour", "Zurück", "Volver", "Quay lại"));
        entries.Add("Lab.Confirm", new("Confirm", "Conferma", "Confirmer", "Bestätigen", "Confirmar", "Xác nhận"));
        entries.Add("Lab.Cancel", new("Cancel", "Annulla", "Annuler", "Abbrechen", "Cancelar", "Hủy"));
        entries.Add("Lab.Disabled", new("Enable this experiment with hm --skills first.", "Abilita prima l’esperimento con hm --skills.", "Activez d’abord l’expérience avec hm --skills.", "Zuerst das Experiment mit hm --skills aktivieren.", "Activa primero el experimento con hm --skills.", "Trước tiên bật thử nghiệm bằng hm --skills."));
        entries.Add("Lab.Activate", new("Enable this exact package", "Abilita questo pacchetto", "Activer ce paquet précis", "Dieses Paket aktivieren", "Habilitar este paquete", "Bật đúng gói này"));
        entries.Add("Lab.Deactivate", new("Disable this skill", "Disabilita questa skill", "Désactiver cette compétence", "Diesen Skill deaktivieren", "Deshabilitar esta skill", "Tắt kỹ năng này"));
        entries.Add("Lab.Select", new("Use in subsequent questions", "Usa nelle prossime domande", "Utiliser pour les prochaines questions", "Für folgende Fragen verwenden", "Usar en las próximas preguntas", "Dùng cho các câu hỏi tiếp theo"));
        entries.Add("Lab.ClearSelection", new("Clear manual skill selection", "Rimuovi selezione manuale", "Effacer la sélection manuelle", "Manuelle Auswahl löschen", "Borrar selección manual", "Xóa lựa chọn thủ công"));
        entries.Add("Lab.Automatic", new("Toggle contextual skill selection", "Attiva/disattiva selezione contestuale", "Basculer la sélection contextuelle", "Kontextuelle Auswahl umschalten", "Alternar selección contextual", "Bật/tắt chọn theo ngữ cảnh"));
        entries.Add("Lab.Import", new("Import a skill ZIP", "Importa uno ZIP di una skill", "Importer un ZIP de compétence", "Skill-ZIP importieren", "Importar ZIP de skill", "Nhập ZIP kỹ năng"));
        entries.Add("Lab.Path", new("File or directory path", "Percorso del file o cartella", "Chemin du fichier ou dossier", "Datei- oder Verzeichnispfad", "Ruta del archivo o carpeta", "Đường dẫn tệp hoặc thư mục"));
        entries.Add("Lab.Run", new("Choose an action", "Scegli un’azione", "Choisir une action", "Aktion auswählen", "Elegir acción", "Chọn thao tác"));
        entries.Add("Lab.Enabled", new("Enabled", "Abilitato", "Activé", "Aktiviert", "Habilitado", "Đã bật"));
        entries.Add("Lab.Off", new("Disabled", "Disabilitato", "Désactivé", "Deaktiviert", "Deshabilitado", "Đã tắt"));
        entries.Add("Lab.Active", new("Active skills: {0}", "Skills attive: {0}", "Compétences actives : {0}", "Aktive Skills: {0}", "Skills activas: {0}", "Kỹ năng đang dùng: {0}"));
        entries.Add("Lab.Source", new("Source", "Provenienza", "Source", "Quelle", "Origen", "Nguồn"));
        entries.Add("Lab.Package", new("Package contents", "Contenuto del pacchetto", "Contenu du paquet", "Paketinhalt", "Contenido del paquete", "Nội dung gói"));
        entries.Add("Lab.Capture", new("Toggle capture of future user messages (30 days, current project)", "Attiva/disattiva raccolta messaggi futuri dell’utente (30 giorni, progetto corrente)", "Basculer la collecte des futurs messages utilisateur (30 jours, projet actuel)", "Erfassung künftiger Nutzernachrichten umschalten (30 Tage, aktuelles Projekt)", "Alternar captura de futuros mensajes del usuario (30 días, proyecto actual)", "Bật/tắt lưu tin nhắn người dùng sắp tới (30 ngày, dự án hiện tại)"));
        entries.Add("Lab.CaptureNotice", new("Opt-in capture stores redacted user messages locally. Dream sends selected observations to OpenAI. Disabling capture clears observations and proposals.", "La raccolta facoltativa salva localmente i messaggi utente redatti. Dream invia le osservazioni selezionate a OpenAI. Disabilitare cancella osservazioni e proposte.", "La collecte facultative conserve localement les messages expurgés. Dream envoie les observations choisies à OpenAI. La désactivation efface observations et propositions.", "Die optionale Erfassung speichert bereinigte Nutzernachrichten lokal. Dream sendet ausgewählte Beobachtungen an OpenAI. Deaktivieren löscht Beobachtungen und Vorschläge.", "La captura opcional guarda mensajes depurados localmente. Dream envía observaciones seleccionadas a OpenAI. Desactivarla borra observaciones y propuestas.", "Tùy chọn này lưu tin nhắn đã che thông tin nhạy cảm cục bộ. Dream gửi quan sát đã chọn đến OpenAI. Tắt sẽ xóa quan sát và đề xuất."));
        entries.Add("Lab.Reminder", new("Toggle maintenance reminder at chat start", "Attiva/disattiva promemoria manutenzione a inizio chat", "Basculer le rappel en début de chat", "Wartungshinweis beim Chatstart umschalten", "Alternar recordatorio al iniciar chat", "Bật/tắt nhắc bảo trì khi bắt đầu chat"));
        entries.Add("Lab.Due", new("Memory maintenance is due. Run hm --heartbeat when convenient.", "È disponibile una revisione delle memorie. Avvia hm --heartbeat quando vuoi.", "Révision des mémoires à effectuer. Lancez hm --heartbeat à votre convenance.", "Eine Speicherprüfung ist fällig. Bei Gelegenheit hm --heartbeat starten.", "La revisión de memorias está pendiente. Ejecuta hm --heartbeat cuando quieras.", "Đến hạn kiểm tra ghi nhớ. Chạy hm --heartbeat khi thuận tiện."));
        entries.Add("Lab.Clear", new("Clear captured observations and proposals", "Cancella osservazioni e proposte", "Effacer observations et propositions", "Beobachtungen und Vorschläge löschen", "Borrar observaciones y propuestas", "Xóa quan sát và đề xuất"));
        entries.Add("Lab.Observations", new("Captured observations", "Osservazioni raccolte", "Observations collectées", "Erfasste Beobachtungen", "Observaciones capturadas", "Quan sát đã lưu"));
        entries.Add("Lab.None", new("Nothing to review.", "Niente da valutare.", "Rien à examiner.", "Nichts zu prüfen.", "Nada que revisar.", "Không có gì cần xem xét."));
        entries.Add("Lab.Approve", new("Approve the displayed change", "Approva la modifica mostrata", "Approuver la modification affichée", "Angezeigte Änderung genehmigen", "Aprobar el cambio mostrado", "Phê duyệt thay đổi hiển thị"));
        entries.Add("Lab.Reject", new("Reject proposal", "Scarta proposta", "Rejeter la proposition", "Vorschlag ablehnen", "Rechazar propuesta", "Từ chối đề xuất"));
        entries.Add("Lab.Edit", new("Edit proposed text", "Modifica testo proposto", "Modifier le texte proposé", "Vorgeschlagenen Text bearbeiten", "Editar texto propuesto", "Sửa nội dung đề xuất"));
        entries.Add("Lab.Before", new("Before", "Prima", "Avant", "Vorher", "Antes", "Trước"));
        entries.Add("Lab.After", new("After", "Dopo", "Après", "Nachher", "Después", "Sau"));
        entries.Add("Lab.Reason", new("Reason", "Motivazione", "Motif", "Begründung", "Motivo", "Lý do"));
        entries.Add("Lab.Sources", new("Evidence / source IDs", "Evidenze / ID fonti", "Preuves / ID des sources", "Belege / Quellen-IDs", "Evidencias / ID de fuentes", "Bằng chứng / ID nguồn"));
        entries.Add("Lab.Saved", new("Saved.", "Salvato.", "Enregistré.", "Gespeichert.", "Guardado.", "Đã lưu."));
        entries.Add("Lab.ReviewCount", new("Created {0} proposals. Review with hm --proposals.", "Create {0} proposte. Valutale con hm --proposals.", "{0} propositions créées. Examinez-les avec hm --proposals.", "{0} Vorschläge erstellt. Mit hm --proposals prüfen.", "Se crearon {0} propuestas. Revisa con hm --proposals.", "Đã tạo {0} đề xuất. Xem bằng hm --proposals."));
        entries.Add("Lab.Share", new("Send the displayed evidence to OpenAI for analysis? This uses API tokens.", "Inviare le evidenze mostrate a OpenAI per l’analisi? Consuma token API.", "Envoyer les preuves affichées à OpenAI ? Cela consomme des jetons API.", "Angezeigte Belege zur Analyse an OpenAI senden? Dies verbraucht API-Tokens.", "¿Enviar las evidencias mostradas a OpenAI? Consume tokens API.", "Gửi bằng chứng hiển thị đến OpenAI để phân tích? Thao tác dùng token API."));
        entries.Add("Lab.NeedSessions", new("Dream needs observations from at least two different sessions.", "Dream richiede osservazioni da almeno due sessioni diverse.", "Dream nécessite au moins deux sessions d’observations.", "Dream benötigt Beobachtungen aus mindestens zwei Sitzungen.", "Dream requiere observaciones de al menos dos sesiones distintas.", "Dream cần quan sát từ ít nhất hai phiên khác nhau."));
        entries.Add("Lab.ManualOnly", new("This package must be enabled again after any file changes.", "Questo pacchetto va riabilitato dopo ogni modifica ai file.", "Ce paquet doit être réactivé après toute modification.", "Nach Dateiänderungen muss dieses Paket erneut aktiviert werden.", "Este paquete debe habilitarse de nuevo tras cualquier cambio.", "Phải bật lại gói này sau mỗi thay đổi tệp."));
        entries.Add("Lab.Arguments", new("PowerShell parameters as a JSON object (no secrets)", "Parametri PowerShell come oggetto JSON (senza segreti)", "Paramètres PowerShell en objet JSON (sans secrets)", "PowerShell-Parameter als JSON-Objekt (ohne Geheimnisse)", "Parámetros PowerShell como objeto JSON (sin secretos)", "Tham số PowerShell dạng đối tượng JSON (không chứa bí mật)"));
        entries.Add("Lab.LastRun", new("Last successful maintenance", "Ultima manutenzione riuscita", "Dernière maintenance réussie", "Letzte erfolgreiche Wartung", "Último mantenimiento correcto", "Lần bảo trì thành công gần nhất"));
        entries.Add("Lab.ReviewButton", new("Proposals", "Proposte", "Propositions", "Vorschläge", "Propuestas", "Đề xuất"));
        entries.Add("Lab.SkillActionInvalid", new("The skill could not complete. Check its parameters, permissions, and supported platform.", "La skill non è riuscita a completare l’azione. Controlla parametri, permessi e piattaforma supportata.", "La compétence n’a pas pu terminer. Vérifiez les paramètres, les autorisations et la plateforme prise en charge.", "Der Skill konnte nicht abgeschlossen werden. Prüfe Parameter, Berechtigungen und unterstützte Plattform.", "La skill no pudo completar la acción. Revisa parámetros, permisos y plataforma compatible.", "Kỹ năng không thể hoàn tất. Kiểm tra tham số, quyền và nền tảng được hỗ trợ."));
        entries.Add("Lab.ForgetNotice", new("Forgetting also permanently clears learning observations and proposals in this scope (all projects for a global memory). Other approved memories and earlier audit records remain.", "Dimenticare cancella definitivamente anche osservazioni e proposte di questo ambito (tutti i progetti per una memoria globale). Le altre memorie approvate e i registri precedenti restano.", "Oublier efface définitivement les observations et propositions de cette portée (tous les projets pour une mémoire globale). Les autres mémoires approuvées et anciennes traces restent.", "Vergessen löscht auch Beobachtungen und Vorschläge dieses Bereichs endgültig (alle Projekte bei globalen Erinnerungen). Andere genehmigte Erinnerungen und frühere Protokolle bleiben.", "Olvidar borra definitivamente observaciones y propuestas de este ámbito (todos los proyectos si es global). Otras memorias aprobadas y registros anteriores permanecen.", "Quên sẽ xóa vĩnh viễn quan sát và đề xuất trong phạm vi này (mọi dự án nếu là ghi nhớ toàn cục). Ghi nhớ đã duyệt khác và nhật ký trước đó vẫn còn."));
        entries.Add("Lab.ConcatInvalid", new("The selected paths or files are invalid, linked, or exceed the concatenation limits.", "I percorsi o i file selezionati non sono validi, sono collegamenti o superano i limiti di concatenazione.", "Les chemins ou fichiers sélectionnés sont invalides, sont des liens ou dépassent les limites de concaténation.", "Die gewählten Pfade oder Dateien sind ungültig, sind Verknüpfungen oder überschreiten die Zusammenführungslimits.", "Las rutas o los archivos seleccionados no son válidos, son enlaces o superan los límites de concatenación.", "Đường dẫn hoặc tệp đã chọn không hợp lệ, là liên kết hoặc vượt giới hạn ghép tệp."));
    }
}
