// SPDX-License-Identifier: MIT

namespace PromptMeUp.Services;

internal static partial class UiTextCatalog
{
    /// <summary>Adds all six translations for explicit reflection consent, evidence review, and memory maintenance.</summary>
    private static void AddReflectionEntries(Dictionary<string, LocalizedText> entries)
    {
        entries.Add("Lab.Retention", new("Learning records expire after 30 days; only the newest 200 observations per project are retained. Clearing evidence also removes its proposals. Approved memories remain until you forget them. Confirmed reflection requests and responses may remain in ordinary local AI history.", "I dati di apprendimento scadono dopo 30 giorni; vengono conservate solo le ultime 200 osservazioni per progetto. Cancellare le evidenze rimuove anche le proposte collegate. Le memorie approvate restano finché non le dimentichi. Richieste e risposte di riflessioni confermate possono restare nella normale cronologia AI locale.", "Les données d’apprentissage expirent après 30 jours ; seules les 200 dernières observations par projet sont conservées. Effacer les preuves supprime leurs propositions. Les mémoires approuvées restent jusqu’à leur suppression. Les requêtes et réponses de réflexion confirmées peuvent rester dans l’historique IA local habituel.", "Lerndaten verfallen nach 30 Tagen; je Projekt bleiben nur die letzten 200 Beobachtungen erhalten. Beleglöschung entfernt auch Vorschläge. Genehmigte Erinnerungen bleiben bis zum Vergessen. Bestätigte Reflexionsanfragen und Antworten können im normalen lokalen KI-Verlauf verbleiben.", "Los datos de aprendizaje caducan tras 30 días; se conservan solo las 200 últimas observaciones por proyecto. Borrar evidencias elimina sus propuestas. Las memorias aprobadas permanecen hasta que las olvides. Las solicitudes y respuestas de reflexión confirmadas pueden quedar en el historial local habitual de IA.", "Dữ liệu học hết hạn sau 30 ngày; chỉ giữ 200 quan sát mới nhất mỗi dự án. Xóa bằng chứng cũng xóa đề xuất liên quan. Ghi nhớ đã duyệt tồn tại đến khi bạn quên chúng. Yêu cầu và phản hồi suy ngẫm đã xác nhận có thể vẫn còn trong lịch sử AI cục bộ thông thường."));
        entries.Add("Lab.BoundedEvidence", new("Only the complete records displayed above will be sent. {0} records were omitted to respect the request limit; findings cover this batch only.", "Verranno inviati solo i record completi mostrati sopra. {0} record esclusi per rispettare il limite della richiesta; i risultati riguardano solo questo gruppo.", "Seuls les éléments complets affichés seront envoyés. {0} éléments ont été exclus pour respecter la limite ; les résultats concernent uniquement ce lot.", "Nur die angezeigten vollständigen Datensätze werden gesendet. {0} Datensätze wurden wegen des Anfragelimits ausgelassen; Ergebnisse gelten nur für diese Auswahl.", "Solo se enviarán los registros completos mostrados. Se omitieron {0} para respetar el límite; los resultados cubren solo este grupo.", "Chỉ gửi bản ghi đầy đủ hiển thị ở trên. Đã bỏ qua {0} bản ghi để tuân thủ giới hạn; kết quả chỉ áp dụng cho nhóm này."));
        entries.Add("Lab.BatchTooSmall", new("The request limit cannot fit enough complete evidence. Increase the message limit or shorten the saved content before retrying.", "Il limite della richiesta non contiene abbastanza evidenze complete. Aumenta il limite dei messaggi o accorcia il contenuto salvato prima di riprovare.", "La limite ne permet pas assez de preuves complètes. Augmentez la limite des messages ou raccourcissez le contenu avant de réessayer.", "Das Anfragelimit reicht nicht für genügend vollständige Belege. Nachrichtenlimit erhöhen oder gespeicherte Inhalte kürzen und erneut versuchen.", "El límite no permite suficientes evidencias completas. Aumenta el límite de mensajes o acorta el contenido guardado antes de reintentar.", "Giới hạn yêu cầu không đủ chứa bằng chứng đầy đủ. Tăng giới hạn tin nhắn hoặc rút ngắn nội dung đã lưu rồi thử lại."));
        entries.Add("Lab.DuplicateReason", new("These saved memories contain exactly the same text in the same scope. Merge them into one reviewed memory.", "Queste memorie contengono esattamente lo stesso testo nello stesso ambito. Uniscile in una sola memoria dopo la revisione.", "Ces mémoires contiennent exactement le même texte dans la même portée. Fusionnez-les après examen.", "Diese Erinnerungen enthalten denselben Text im selben Bereich. Nach Prüfung zu einer Erinnerung zusammenführen.", "Estas memorias contienen el mismo texto en el mismo ámbito. Únelas en una memoria revisada.", "Các ghi nhớ có nội dung giống hệt trong cùng phạm vi. Hợp nhất thành một ghi nhớ sau khi xem xét."));
        entries.Add("Lab.Archived", new("Remove the displayed memories from saved memory.", "Rimuovi le memorie mostrate dalla memoria salvata.", "Retirer les mémoires affichées des mémoires enregistrées.", "Angezeigte Erinnerungen aus dem Speicher entfernen.", "Quitar las memorias mostradas de la memoria guardada.", "Xóa các ghi nhớ hiển thị khỏi bộ nhớ đã lưu."));
        entries.Add("Lab.NoPrevious", new("No saved memory will be replaced.", "Nessuna memoria salvata verrà sostituita.", "Aucune mémoire enregistrée ne sera remplacée.", "Keine gespeicherte Erinnerung wird ersetzt.", "No se reemplazará ninguna memoria guardada.", "Không ghi đè ghi nhớ đã lưu nào."));
        entries.Add("Lab.Unchanged", new("Saved memories remain unchanged.", "Le memorie salvate restano invariate.", "Les mémoires enregistrées restent inchangées.", "Gespeicherte Erinnerungen bleiben unverändert.", "Las memorias guardadas quedan sin cambios.", "Ghi nhớ đã lưu không thay đổi."));
        entries.Add("Lab.FlagNotice", new("This is an informational finding. You can dismiss it; changing a memory requires the memory manager.", "Questa è una segnalazione informativa. Puoi scartarla; per modificare una memoria usa il gestore memorie.", "Ce signalement est informatif. Vous pouvez le rejeter ; utilisez le gestionnaire pour modifier une mémoire.", "Dies ist nur ein Hinweis. Er kann verworfen werden; Erinnerungen werden in der Speicherverwaltung geändert.", "Es una observación informativa. Puedes descartarla; usa el gestor de memorias para modificar una memoria.", "Đây là nhận xét để tham khảo. Bạn có thể bỏ qua; muốn sửa ghi nhớ hãy dùng trình quản lý ghi nhớ."));
        entries.Add("Lab.Operation", new("Change", "Modifica", "Modification", "Änderung", "Cambio", "Thay đổi"));
        entries.Add("Lab.Kind", new("Memory type", "Tipo di memoria", "Type de mémoire", "Erinnerungstyp", "Tipo de memoria", "Loại ghi nhớ"));
        entries.Add("Lab.StartCapture", new("Capture future completed user messages for this project?", "Raccogliere i futuri messaggi utente completati per questo progetto?", "Collecter les futurs messages utilisateur terminés pour ce projet ?", "Künftige abgeschlossene Nutzernachrichten für dieses Projekt erfassen?", "¿Capturar futuros mensajes completados del usuario para este proyecto?", "Lưu các tin nhắn người dùng hoàn tất sắp tới cho dự án này?"));
        entries.Add("Lab.StopCapture", new("Stop capture and clear this project's observations and proposals?", "Interrompere la raccolta e cancellare osservazioni e proposte di questo progetto?", "Arrêter la collecte et effacer les observations et propositions de ce projet ?", "Erfassung beenden und Beobachtungen sowie Vorschläge dieses Projekts löschen?", "¿Detener la captura y borrar observaciones y propuestas de este proyecto?", "Dừng thu thập và xóa quan sát cùng đề xuất của dự án này?"));
        entries.Add("Lab.CaptureRequired", new("Enable observation capture in hm --learning before using Dream.", "Abilita la raccolta delle osservazioni in hm --learning prima di usare Dream.", "Activez la collecte dans hm --learning avant d’utiliser Dream.", "Vor Dream die Beobachtungserfassung in hm --learning aktivieren.", "Activa la captura de observaciones en hm --learning antes de usar Dream.", "Bật thu thập quan sát trong hm --learning trước khi dùng Dream."));
        entries.Add("Lab.ForgetObservation", new("Delete this observation and its derived proposals? Approved memories are not deleted.", "Cancellare questa osservazione e le proposte derivate? Le memorie approvate non vengono cancellate.", "Supprimer cette observation et ses propositions ? Les mémoires approuvées ne sont pas supprimées.", "Diese Beobachtung und abgeleitete Vorschläge löschen? Genehmigte Erinnerungen werden nicht gelöscht.", "¿Borrar esta observación y sus propuestas derivadas? Las memorias aprobadas no se borran.", "Xóa quan sát này và đề xuất liên quan? Không xóa các ghi nhớ đã duyệt."));
        entries.Add("Lab.LocalMaintenance", new("Local duplicate review completed. OpenAI analysis below is optional.", "Revisione locale dei duplicati completata. L’analisi OpenAI seguente è facoltativa.", "Examen local des doublons terminé. L’analyse OpenAI suivante est facultative.", "Lokale Duplikatprüfung abgeschlossen. Die folgende OpenAI-Analyse ist optional.", "Revisión local de duplicados completada. El análisis de OpenAI siguiente es opcional.", "Đã kiểm tra bản trùng cục bộ. Phân tích OpenAI bên dưới là tùy chọn."));
        entries.Add("Lab.Never", new("Never", "Mai", "Jamais", "Nie", "Nunca", "Chưa bao giờ"));
        entries.Add("Lab.Operation.add", new("Add", "Aggiungi", "Ajouter", "Hinzufügen", "Añadir", "Thêm"));
        entries.Add("Lab.Operation.merge", new("Merge", "Unisci", "Fusionner", "Zusammenführen", "Unir", "Hợp nhất"));
        entries.Add("Lab.Operation.archive", new("Remove", "Rimuovi", "Retirer", "Entfernen", "Quitar", "Xóa"));
        entries.Add("Lab.Operation.flag", new("Review finding", "Segnalazione da valutare", "Signalement à examiner", "Hinweis prüfen", "Observación para revisar", "Nhận xét cần xem xét"));
        entries.Add("Lab.Kind.memory", new("Fact", "Fatto", "Fait", "Fakt", "Hecho", "Sự kiện"));
        entries.Add("Lab.Kind.lesson", new("Lesson", "Lezione", "Leçon", "Erkenntnis", "Lección", "Bài học"));
        entries.Add("Lab.Kind.correction", new("Correction", "Correzione", "Correction", "Korrektur", "Corrección", "Sửa sai"));
        entries.Add("Lab.Kind.preference", new("Preference", "Preferenza", "Préférence", "Präferenz", "Preferencia", "Sở thích"));
    }
}
