// SPDX-License-Identifier: MIT

namespace PromptMeUp.Services;

internal static partial class UiTextCatalog
{
    /// <summary>Adds all six translations for explicit reflection consent, evidence review, and memory maintenance.</summary>
    private static void AddReflectionEntries(Dictionary<string, LocalizedText> entries)
    {
        entries.Add("Lab.Retention", new("Only the newest 200 collected messages are kept globally. Messages and suggestions older than 30 days are removed when you next use these records. Deleting messages also deletes their suggestions. Saved memories remain until you delete them. Confirmed OpenAI analyses may remain in ordinary local history.", "Si conservano globalmente solo i 200 messaggi raccolti più recenti. Messaggi e suggerimenti oltre 30 giorni vengono rimossi quando usi di nuovo questi dati. Cancellare i messaggi elimina anche i suggerimenti collegati. I ricordi salvati restano finché non li elimini. Le analisi OpenAI confermate possono restare nella normale cronologia locale.", "Seuls les 200 derniers messages collectés sont conservés globalement. Messages et suggestions de plus de 30 jours sont supprimés à leur prochaine utilisation. Supprimer les messages efface aussi leurs suggestions. Les souvenirs enregistrés restent jusqu’à leur suppression. Les analyses OpenAI confirmées peuvent rester dans l’historique local habituel.", "Global bleiben nur die neuesten 200 erfassten Nachrichten erhalten. Nachrichten und Vorschläge über 30 Tage werden bei der nächsten Nutzung dieser Daten entfernt. Das Löschen von Nachrichten entfernt auch ihre Vorschläge. Gespeicherte Erinnerungen bleiben, bis du sie löschst. Bestätigte OpenAI-Analysen können im normalen lokalen Verlauf verbleiben.", "Solo se conservan globalmente los 200 mensajes recopilados más recientes. Los mensajes y sugerencias de más de 30 días se eliminan al volver a usar estos datos. Borrar mensajes elimina también sus sugerencias. Los recuerdos guardados permanecen hasta que los borres. Los análisis de OpenAI confirmados pueden quedar en el historial local habitual.", "Chỉ giữ toàn cục 200 tin nhắn đã thu thập mới nhất. Tin nhắn và đề xuất quá 30 ngày được xóa khi bạn dùng lại dữ liệu này. Xóa tin nhắn cũng xóa đề xuất liên quan. Ghi nhớ đã lưu vẫn còn cho đến khi bạn xóa. Các phân tích OpenAI đã xác nhận có thể vẫn còn trong lịch sử cục bộ thông thường."));
        entries.Add("Lab.BoundedEvidence", new("Only the complete records displayed above will be sent. {0} records were omitted to respect the request limit; findings cover this batch only.", "Verranno inviati solo i record completi mostrati sopra. {0} record esclusi per rispettare il limite della richiesta; i risultati riguardano solo questo gruppo.", "Seuls les éléments complets affichés seront envoyés. {0} éléments ont été exclus pour respecter la limite ; les résultats concernent uniquement ce lot.", "Nur die angezeigten vollständigen Datensätze werden gesendet. {0} Datensätze wurden wegen des Anfragelimits ausgelassen; Ergebnisse gelten nur für diese Auswahl.", "Solo se enviarán los registros completos mostrados. Se omitieron {0} para respetar el límite; los resultados cubren solo este grupo.", "Chỉ gửi bản ghi đầy đủ hiển thị ở trên. Đã bỏ qua {0} bản ghi để tuân thủ giới hạn; kết quả chỉ áp dụng cho nhóm này."));
        entries.Add("Lab.BatchTooSmall", new("The request limit cannot fit enough complete evidence. Increase the message limit or shorten the saved content before retrying.", "Il limite della richiesta non contiene abbastanza evidenze complete. Aumenta il limite dei messaggi o accorcia il contenuto salvato prima di riprovare.", "La limite ne permet pas assez de preuves complètes. Augmentez la limite des messages ou raccourcissez le contenu avant de réessayer.", "Das Anfragelimit reicht nicht für genügend vollständige Belege. Nachrichtenlimit erhöhen oder gespeicherte Inhalte kürzen und erneut versuchen.", "El límite no permite suficientes evidencias completas. Aumenta el límite de mensajes o acorta el contenido guardado antes de reintentar.", "Giới hạn yêu cầu không đủ chứa bằng chứng đầy đủ. Tăng giới hạn tin nhắn hoặc rút ngắn nội dung đã lưu rồi thử lại."));
        entries.Add("Lab.DuplicateReason", new("These saved memories contain exactly the same text. Merge them into one reviewed memory.", "Questi ricordi contengono esattamente lo stesso testo. Uniscili in un solo ricordo dopo la revisione.", "Ces souvenirs contiennent exactement le même texte. Fusionnez-les après examen.", "Diese Erinnerungen enthalten genau denselben Text. Nach Prüfung zu einer Erinnerung zusammenführen.", "Estos recuerdos contienen exactamente el mismo texto. Únelos en un recuerdo revisado.", "Các ghi nhớ có nội dung giống hệt nhau. Hợp nhất thành một ghi nhớ sau khi xem xét."));
        entries.Add("Lab.Archived", new("Remove the displayed memories from saved memory.", "Rimuovi le memorie mostrate dalla memoria salvata.", "Retirer les mémoires affichées des mémoires enregistrées.", "Angezeigte Erinnerungen aus dem Speicher entfernen.", "Quitar las memorias mostradas de la memoria guardada.", "Xóa các ghi nhớ hiển thị khỏi bộ nhớ đã lưu."));
        entries.Add("Lab.NoPrevious", new("No saved memory will be replaced.", "Nessuna memoria salvata verrà sostituita.", "Aucune mémoire enregistrée ne sera remplacée.", "Keine gespeicherte Erinnerung wird ersetzt.", "No se reemplazará ninguna memoria guardada.", "Không ghi đè ghi nhớ đã lưu nào."));
        entries.Add("Lab.Unchanged", new("Saved memories remain unchanged.", "Le memorie salvate restano invariate.", "Les mémoires enregistrées restent inchangées.", "Gespeicherte Erinnerungen bleiben unverändert.", "Las memorias guardadas quedan sin cambios.", "Ghi nhớ đã lưu không thay đổi."));
        entries.Add("Lab.FlagNotice", new("This is an informational finding. You can dismiss it; changing a memory requires the memory manager.", "Questa è una segnalazione informativa. Puoi scartarla; per modificare una memoria usa il gestore memorie.", "Ce signalement est informatif. Vous pouvez le rejeter ; utilisez le gestionnaire pour modifier une mémoire.", "Dies ist nur ein Hinweis. Er kann verworfen werden; Erinnerungen werden in der Speicherverwaltung geändert.", "Es una observación informativa. Puedes descartarla; usa el gestor de memorias para modificar una memoria.", "Đây là nhận xét để tham khảo. Bạn có thể bỏ qua; muốn sửa ghi nhớ hãy dùng trình quản lý ghi nhớ."));
        entries.Add("Lab.Operation", new("Change", "Modifica", "Modification", "Änderung", "Cambio", "Thay đổi"));
        entries.Add("Lab.Kind", new("Memory type", "Tipo di ricordo", "Type de souvenir", "Erinnerungstyp", "Tipo de recuerdo", "Loại ghi nhớ"));
        entries.Add("Lab.StartCapture", new("Collect your future messages after each completed exchange?", "Raccogliere i tuoi prossimi messaggi dopo ogni scambio completato?", "Collecter vos prochains messages après chaque échange terminé ?", "Deine künftigen Nachrichten nach jedem abgeschlossenen Austausch erfassen?", "¿Recopilar tus próximos mensajes después de cada intercambio completado?", "Thu thập tin nhắn tiếp theo của bạn sau mỗi lượt trao đổi hoàn tất?"));
        entries.Add("Lab.StopCapture", new("Stop collecting messages and delete collected messages and suggestions? Saved memories remain.", "Interrompere la raccolta e cancellare messaggi raccolti e suggerimenti? I ricordi salvati restano.", "Arrêter la collecte et supprimer les messages collectés et suggestions ? Les souvenirs enregistrés restent.", "Erfassung stoppen und erfasste Nachrichten sowie Vorschläge löschen? Gespeicherte Erinnerungen bleiben.", "¿Dejar de recopilar mensajes y borrar los mensajes recopilados y sugerencias? Los recuerdos guardados permanecen.", "Dừng thu thập và xóa tin nhắn đã thu thập cùng đề xuất? Ghi nhớ đã lưu vẫn còn."));
        entries.Add("Lab.CaptureRequired", new("Turn on message collection in hm --learning before using Dream.", "Attiva la raccolta dei messaggi con hm --learning prima di usare Dream.", "Activez la collecte des messages avec hm --learning avant d’utiliser Dream.", "Vor Dream die Nachrichtenerfassung mit hm --learning aktivieren.", "Activa la recopilación de mensajes con hm --learning antes de usar Dream.", "Bật thu thập tin nhắn bằng hm --learning trước khi dùng Dream."));
        entries.Add("Lab.ForgetObservation", new("Delete this collected message and its suggestions? Saved memories are not deleted.", "Cancellare questo messaggio raccolto e i suggerimenti collegati? I ricordi salvati non vengono cancellati.", "Supprimer ce message collecté et ses suggestions ? Les souvenirs enregistrés ne sont pas supprimés.", "Diese erfasste Nachricht und ihre Vorschläge löschen? Gespeicherte Erinnerungen werden nicht gelöscht.", "¿Borrar este mensaje recopilado y sus sugerencias? Los recuerdos guardados no se borran.", "Xóa tin nhắn đã thu thập này và các đề xuất liên quan? Không xóa ghi nhớ đã lưu."));
        entries.Add("Lab.LocalMaintenance", new("Local duplicate review completed. OpenAI analysis below is optional.", "Revisione locale dei duplicati completata. L’analisi OpenAI seguente è facoltativa.", "Examen local des doublons terminé. L’analyse OpenAI suivante est facultative.", "Lokale Duplikatprüfung abgeschlossen. Die folgende OpenAI-Analyse ist optional.", "Revisión local de duplicados completada. El análisis de OpenAI siguiente es opcional.", "Đã kiểm tra bản trùng cục bộ. Phân tích OpenAI bên dưới là tùy chọn."));
        entries.Add("Lab.Never", new("Never", "Mai", "Jamais", "Nie", "Nunca", "Chưa bao giờ"));
        entries.Add("Lab.Operation.add", new("Add", "Aggiungi", "Ajouter", "Hinzufügen", "Añadir", "Thêm"));
        entries.Add("Lab.Operation.merge", new("Merge", "Unisci", "Fusionner", "Zusammenführen", "Unir", "Hợp nhất"));
        entries.Add("Lab.Operation.archive", new("Remove", "Rimuovi", "Retirer", "Entfernen", "Quitar", "Xóa"));
        entries.Add("Lab.Operation.flag", new("Review finding", "Segnalazione da valutare", "Signalement à examiner", "Hinweis prüfen", "Observación para revisar", "Nhận xét cần xem xét"));
        entries.Add("Lab.Kind.memory", new("Fact", "Fatto", "Fait", "Fakt", "Hecho", "Sự kiện"));
        entries.Add("Lab.Kind.lesson", new("Lesson", "Lezione", "Leçon", "Erkenntnis", "Lección", "Bài học"));
        entries.Add("Lab.Kind.correction", new("Correction", "Correzione", "Correction", "Korrektur", "Corrección", "Sửa sai"));
        entries.Add("Lab.Kind.preference", new("Preference", "Preferenza", "Préférence", "Präferenz", "Preferencia", "Sở thích"));
    }
}
