// SPDX-License-Identifier: MIT

namespace PromptMeUp.Services;

internal static partial class UiTextCatalog
{
    /// <summary>Adds the six supported translations for explicitly reviewed local reminders.</summary>
    private static void AddReminderEntries(Dictionary<string, LocalizedText> entries)
    {
        entries.Add("Reminder.Title", new("Project reminders", "Promemoria del progetto", "Rappels du projet", "Projekterinnerungen", "Recordatorios del proyecto", "Lời nhắc của dự án"));
        entries.Add("Reminder.Notice", new("Reminders are local to this project. They appear only when an active chat reaches its next input prompt, not as background or system notifications. Disabling the skill pauses delivery. Shown or cancelled reminders are deleted; at most 50 can be pending.", "I promemoria sono locali a questo progetto. Appaiono solo quando una chat attiva arriva alla prossima richiesta di input, non come notifiche in background o di sistema. Disattivare la skill sospende la consegna. Quelli mostrati o annullati vengono eliminati; massimo 50 in attesa.", "Les rappels sont locaux au projet. Ils apparaissent seulement lorsqu’un chat actif atteint sa prochaine invite, sans notification système ni tâche de fond. Désactiver la skill suspend leur affichage. Les rappels affichés ou annulés sont supprimés ; 50 peuvent rester en attente.", "Erinnerungen gelten lokal für dieses Projekt. Sie erscheinen nur beim nächsten Eingabeprompt eines aktiven Chats, nicht im Hintergrund oder als Systemmeldung. Deaktivieren der Skill pausiert die Anzeige. Angezeigte oder stornierte Erinnerungen werden gelöscht; höchstens 50 bleiben offen.", "Los recordatorios son locales a este proyecto. Aparecen solo cuando un chat activo llega a su siguiente entrada, sin avisos de sistema ni tareas en segundo plano. Desactivar la skill pausa los avisos. Los mostrados o cancelados se borran; se permiten hasta 50 pendientes.", "Lời nhắc được lưu cục bộ cho dự án này. Chỉ hiển thị khi cuộc trò chuyện đang mở đến lần nhập tiếp theo, không có thông báo hệ thống hay tác vụ nền. Tắt skill sẽ tạm dừng hiển thị. Lời nhắc đã hiện hoặc hủy sẽ bị xóa; tối đa 50 lời nhắc chờ."));
        entries.Add("Reminder.Pending", new("Pending", "In attesa", "En attente", "Ausstehend", "Pendientes", "Đang chờ"));
        entries.Add("Reminder.Create", new("New reminder", "Nuovo promemoria", "Nouveau rappel", "Neue Erinnerung", "Nuevo recordatorio", "Lời nhắc mới"));
        entries.Add("Reminder.At", new("When (14:30, 3pm, or ISO date with offset)", "Quando (14:30, 3pm o data ISO con fuso)", "Quand (14:30, 3pm ou date ISO avec décalage)", "Wann (14:30, 3pm oder ISO-Datum mit Offset)", "Cuándo (14:30, 3pm o fecha ISO con zona)", "Thời điểm (14:30, 3pm hoặc ngày ISO có múi giờ)"));
        entries.Add("Reminder.Message", new("Note (up to 500 characters; no secrets)", "Nota (massimo 500 caratteri; niente segreti)", "Note (500 caractères maximum ; aucun secret)", "Notiz (bis 500 Zeichen; keine Geheimnisse)", "Nota (hasta 500 caracteres; sin secretos)", "Ghi chú (tối đa 500 ký tự; không chứa bí mật)"));
        entries.Add("Reminder.ConfirmCreate", new("Save this reminder for the date and offset shown above?", "Salvare questo promemoria per la data e il fuso mostrati sopra?", "Enregistrer ce rappel pour la date et le décalage affichés ?", "Diese Erinnerung für Datum und Offset oben speichern?", "¿Guardar este recordatorio para la fecha y zona mostradas?", "Lưu lời nhắc này theo ngày và múi giờ ở trên?"));
        entries.Add("Reminder.ConfirmCancel", new("Delete this reminder?", "Eliminare questo promemoria?", "Supprimer ce rappel ?", "Diese Erinnerung löschen?", "¿Eliminar este recordatorio?", "Xóa lời nhắc này?"));
        entries.Add("Reminder.Cancelled", new("Reminder deleted.", "Promemoria eliminato.", "Rappel supprimé.", "Erinnerung gelöscht.", "Recordatorio eliminado.", "Đã xóa lời nhắc."));
        entries.Add("Reminder.Due", new("Reminder — {0}: {1}", "Promemoria — {0}: {1}", "Rappel — {0} : {1}", "Erinnerung — {0}: {1}", "Recordatorio — {0}: {1}", "Lời nhắc — {0}: {1}"));
        entries.Add("Reminder.Limit", new("This project already has 50 pending reminders. Cancel one before adding another.", "Questo progetto ha già 50 promemoria in attesa. Annullane uno prima di aggiungerne un altro.", "Ce projet compte déjà 50 rappels en attente. Annulez-en un avant d’en ajouter un autre.", "Dieses Projekt hat bereits 50 offene Erinnerungen. Vor dem Hinzufügen eine löschen.", "Este proyecto ya tiene 50 recordatorios pendientes. Cancela uno antes de añadir otro.", "Dự án đã có 50 lời nhắc chờ. Hủy một lời nhắc trước khi thêm mới."));
        entries.Add("Reminder.InvalidNote", new("Use a non-empty, single-line note of at most 500 characters without credentials.", "Usa una nota non vuota su una sola riga, di massimo 500 caratteri e senza credenziali.", "Utilisez une note non vide d’une seule ligne, de 500 caractères maximum, sans identifiants secrets.", "Eine nicht leere, einzeilige Notiz mit höchstens 500 Zeichen und ohne Zugangsdaten verwenden.", "Usa una nota de una sola línea, no vacía, con hasta 500 caracteres y sin credenciales.", "Dùng ghi chú một dòng, không trống, tối đa 500 ký tự và không chứa thông tin đăng nhập."));
        entries.Add("Reminder.InvalidTime", new("Enter a future ISO date with an explicit offset (2030-05-20T14:30:00+02:00 or Z), or a clock time such as 14:30 or 3pm for its next local occurrence. Ambiguous or skipped daylight-saving times require an explicit offset.", "Inserisci una data ISO futura con fuso esplicito (2030-05-20T14:30:00+02:00 o Z), oppure un orario come 14:30 o 3pm per la prossima occorrenza locale. Gli orari ambigui o saltati dall’ora legale richiedono un fuso esplicito.", "Saisissez une date ISO future avec décalage explicite (2030-05-20T14:30:00+02:00 ou Z), ou une heure comme 14:30 ou 3pm pour sa prochaine occurrence locale. Les heures ambiguës ou sautées par le changement d’heure exigent un décalage explicite.", "Ein künftiges ISO-Datum mit explizitem Offset eingeben (2030-05-20T14:30:00+02:00 oder Z), oder eine Uhrzeit wie 14:30 oder 3pm für das nächste lokale Auftreten. Mehrdeutige oder durch Zeitumstellung übersprungene Zeiten erfordern einen expliziten Offset.", "Introduce una fecha ISO futura con zona explícita (2030-05-20T14:30:00+02:00 o Z), o una hora como 14:30 o 3pm para su próxima aparición local. Las horas ambiguas u omitidas por el cambio horario requieren una zona explícita.", "Nhập ngày ISO tương lai có múi giờ rõ ràng (2030-05-20T14:30:00+02:00 hoặc Z), hoặc giờ như 14:30 hay 3pm cho lần tiếp theo theo giờ địa phương. Giờ không rõ ràng hoặc bị bỏ qua do đổi giờ mùa hè cần múi giờ rõ ràng."));
    }
}
